#pragma once

#define DISPLAY_FEATURES_Y 200
#define DISPLAY_OPTIONS_Y 300
#define DISPLAY_FEATURES_FONTSIZE 7
#define DISPLAY_FEATURES_FONTSIZE_SELECTED 9.9f
#define DISPLAY_FEATURES_FONTALPHA 127
#define DISPLAY_FEATURES_FONTALPHA_SELECTED 255
#define DISPLAY_FEATURES_SPACING 25
#define DISPLAY_OPTIONS_WIDTH 800
#define DISPLAY_SIZE_X 1000
#define DISPLAY_SIZE_Y 1000
#define DISPLAY_CENTER_X (DISPLAY_SIZE_X/2)
#define DISPLAY_CENTER_Y (DISPLAY_SIZE_Y/2)