
#include "comportNames.hpp"

std::string GetComportName(std::string aiModel, int index) {
  static std::map<std::pair<std::string, int>, std::string> cache;

  auto cacheKey = std::make_pair(aiModel, index);
  auto cacheIt = cache.find(cacheKey);
  if (cacheIt != cache.end()) {
    return cacheIt->second;
  }

  auto it = comportNames.find(aiModel);
  if (it != comportNames.end() && index >= 0 && index < it->second.size()) {
    cache[cacheKey] = it->second[index];
    return it->second[index];
  }

  std::string fallbackResult = "Comport #" + std::to_string(index);
  cache[cacheKey] = fallbackResult;
  return fallbackResult;
}

std::string GetReflexName(std::string aiModel, int index) {
  static std::map<std::pair<std::string, int>, std::string> cache;

  auto cacheKey = std::make_pair(aiModel, index);
  auto cacheIt = cache.find(cacheKey);
  if (cacheIt != cache.end()) {
    return cacheIt->second;
  }

  auto it = reflexNames.find(aiModel);
  if (it != reflexNames.end() && index >= 0 && index < it->second.size()) {
    cache[cacheKey] = it->second[index];
    return it->second[index];
  }

  std::string fallbackResult = "Reflex #" + std::to_string(index);
  cache[cacheKey] = fallbackResult;
  return fallbackResult;
}

int GetComportIndex(std::string aiModel, const std::string& name) {
  static std::map<std::pair<std::string, std::string>, int> cache;

  auto cacheKey = std::make_pair(aiModel, name);
  auto cacheIt = cache.find(cacheKey);
  if (cacheIt != cache.end()) {
    return cacheIt->second;
  }

  auto it = comportNames.find(aiModel);
  if (it != comportNames.end()) {
    const auto& names = it->second;
    for (size_t i = 0; i < names.size(); ++i) {
      if (names[i] == name) {
        cache[cacheKey] = static_cast<int>(i);
        return static_cast<int>(i);
      }
    }
  }

  // Not found
  cache[cacheKey] = -1;
  return -1;
}

int GetReflexIndex(std::string aiModel, const std::string& name) {
  static std::map<std::pair<std::string, std::string>, int> cache;

  auto cacheKey = std::make_pair(aiModel, name);
  auto cacheIt = cache.find(cacheKey);
  if (cacheIt != cache.end()) {
    return cacheIt->second;
  }

  auto it = reflexNames.find(aiModel);
  if (it != reflexNames.end()) {
    const auto& names = it->second;
    for (size_t i = 0; i < names.size(); ++i) {
      if (names[i] == name) {
        cache[cacheKey] = static_cast<int>(i);
        return static_cast<int>(i);
      }
    }
  }

  // Not found
  cache[cacheKey] = -1;
  return -1;
}


const std::unordered_map<std::string, std::vector<std::string>> comportNames = {
    {"Alw_Explosion_model", { "SUN_Flash_init", "OLD_c_boom", "CHR_wait_until_dead", "SUN_c_boo_paf" }},
    {"ELR_mLaveBloup", { "ELR_C_LaveBloup_00_Init", "ELR_C_LaveBloup_01_Normal2" }},
    {"LevelAstro_00", { "YLT_InitLevel" }},
    {"MIC_Obus_Complexe", { "MIC_ObusC_INIT", "MIC_ObusC_TombeAuSol", "MIC_ObusC_Surveille", "MIC_ObusC_Fatigue", "MIC_ObusC_Attaque", "MIC_ObusC_LeRodeo", "MIC_ObusC_FinDuRodeo", "MIC_ObusC_ReInit", "MIC_ObusC_AttendGenerateur", "MIC_ObusC_FinALaZorro", "MIC_ObusC_FinAttaque", "MIC_ObusC_Destruction", "MIC_ObusC_Plane", "MIC_ObusC_Delai", "MIC_ObusC_Crash", "MIC_ObusC_AuSol", "MIC_ObusC_ChuteLibre", "MIC_ObusC_DebutRodeo", "MIC_ObusC_Vide", "MIC_ObusC_Destruction_Suite", "MIC_ObusC_SynchroAvecRay" }},
    {"CHR_lums_basic", { "CHR_basic_init", "CHR_basic_go" }},
    {"MIC_FinDeMap_Simple", { "MIC_FDM_INIT", "MIC_FDM_ChargeMap", "MIC_FDM_Surveille" }},
    {"OLD_porte", { "OLD_porte_init", "OLD_porte_normal", "OLD_porte_flag", "OLD_porte_ouverte", "MIC_porte_kunkou", "FRG_Porte_CB28" }},
    {"CHR_tronc_pic", { "CHR_tronc_pic_init" }},
    {"MIC_SbireNinja", { "MIC_Ninja_INIT", "MIC_ninja_PrepareAttak", "MIC_Ninja_Retombe", "MIC_Ninja_Tape", "MIC_Ninja_Saute", "MIC_Ninja_Tire", "MIC_Ninja_Delai", "MIC_Ninja_Mort", "MIC_Ninja_PrepareSaut", "MIC_Ninja_Reinit", "MIC_Ninja_YoupiRay", "MIC_Ninja_YoupiFin" }},
    {"MIC_GenNFumees", { "MIC_GNF_INIT", "MIC_GNF_Fume" }},
    {"ARG_MegaShoot", { "ARG_MS_init", "ARG_MS_detect" }},
    {"SUN_Cam_Oriente", { "SUN_Cam_Bloc_Init", "SUN_Cam_Bloc_Normal", "SUN_Cam_Oriente_Tunnel", "DS1_Cam_Oriente_NoLeft_NoRight" }},
    {"FRG_Generateur", { "STN_generateur_init", "MRC_generateur_Inactif", "MRC_generateur_Actif" }},
    {"SDZ_EtatAOJ", { "SDZ_Etat_0_Init", "SDZ_Etat_1_Resume", "SDZ_Etat_2_FadeIn", "SDZ_Etat_3_Attente", "SDZ_Etat_4_FadeOut", "SDZ_Etat_5_Pause" }},
    {"MIC_CameraCinoche", { "MIC_Cinoche_INIT", "MIC_Cinoche_Detect_Zone", "MIC_Cinoche_Detect_CB28", "MIC_Cinoche_Detect_EtatRay", "MIC_Cinoche_CestParti", "MIC_Cinoche_JeFilme", "MIC_Cinoche_Fini", "MIC_Cinoche_Pause" }},
    {"MIC_RetientRay", { "MIC_RR_INIT", "MIC_RR_Boucle" }},
    {"DS1_BouclantGlobal", { "DS1_BouclantMarais", "DS1_BouclantCave", "DS1_BouclantLaser", "DS1_BouclantLaveDure", "DS1_BouclantLaveFall", "DS1_BouclantLaveLiq", "DS1_BouclantLaveSem", "DS1_BouclantOrage", "DS1_BouclantCascade", "DS1_BouclantEgout", "DS1_BouclantForet", "DS1_BouclantForet2", "DS1_BouclantRiviere", "DS1_BouclantRiviere2", "DS1_BouclantVent", "DS1_BouclantKaka", "DS1_BouclantAlarm", "DS1_BouclanTekno", "DS1_BouclantFrottePierre", "DS1_InitSoundBigShip", "DS1_BouclantPluie" }},
    {"OLD_interrupteur", { "STN_Switch_init", "STN_Switch_check", "STN_Switch_glisse", "STN_Switch_retour", "STN_Switch_activate", "STN_Switch_target" }},
    {"Alw_Lums_Model", { "STH_lum_init", "FRG_Lum_Rien", "STN_Lums_vert_catch", "STN_Lums_vert_go", "STH_lum_virevolte", "STH_lum_deplacement" }},
    {"YLT_RaymanModel", { "YLT_Init", "YLT_Attente", "YLT_SautReception", "YLT_SautMontee", "YLT_Helico", "BNT_Nage", "YLT_BlocMode", "BNT_Grappin", "YLT_GiBlocMode", "YLT_Reinit", "YLT_Desactive", "YLT_EntreDeux", "YLT_EntreDeuxAvance", "YLT_EntreDeuxRecul", "CHG_RaymanPaf", "CHG_RayPafAir", "CHG_RayPafEau", "CHG_RayPafEcrase", "YLT_PafSol", "YLT_TonneauFuseeComport", "YLT_Vide", "BNT_RayPafAttendLaMort", "YLT_PafGi", "YLT_ChuteInfinie", "YLT_SautImpulsion", "BNT_DansLeSiegeRusse", "YLT_SautSommet", "YLT_Varappe", "BNT_TonneauAttente", "BNT_TonneauMarcheAvant", "YLT_GiAttente", "YLT_GiMarche", "BNT_AccrocheAuBord", "BNT_AccrocheRemonte", "BNT_NagePlonge", "BNT_NageSaute", "BNT_WalkRunComport", "BNT_AccrocheTentatives", "BNT_NewPatin", "BNT_PafElectrique", "BNT_Atterrissage", "BNT_Basket", "BNT_TransePolochusComport", "BNT_FadeDeLaMort", "BNT_FadeDeLaMortBis", "BNT_InitSuiteEtFin", "IKI_AttenteGrimace" }},
    {"StdCam", { "CHR_Mario", "CHR_MarioGrappin", "CHR_Look", "CHR_MarioVarappe", "CHR_Infini", "BNT_Immobilisee", "CHR_MarioHelico", "CHR_MarioGI", "CHR_Libre", "CHR_MarioNage", "DS1_MarioGlisse" }},
    {"GlobalActorModel", { "CHG_GlobalActorInit", "CHG_GlobalActorLoop" }},
    {"YAM_GenMenuMap", { "YAM_MapInit", "YAM_MapAttenteActivation", "YAM_MapDesactivation", "YAM_MapMenuChangeValeur", "YAM_MapMenuLangue", "YAM_MapMenuLoad", "YAM_MapMenuOptions", "YAM_MapMenuPrincipal", "YAM_MapMenuSound", "YAM_MapMenuVideo", "YAM_MapLivrePolochus", "YAM_MapInit2", "YAM_MapInitLivre", "YAM_MapMenuFinLoad", "MCK_MenuChangeValeurLuminosite", "MCK_MenuResolution", "MCK_Avertissement", "MCK_MenuControl", "MCK_MenuCalibration", "MCK_MenuCalibration2", "MCK_MenuYesNo", "MCK_CheatChangeMap", "MCK_MenuFinNoLoad", "NIK_C_Try60Hz", "NIK_C_Valid60Hz", "NIK_C_Indique4_3_OU_16_9", "NIK_C_CentrageEcran", "NIK_C_Confirm_LOAD_Pour_Ecrasement" }},
    {"ARG_IconeGestionnaire", { "ARG_IG_init", "ARG_IG_main", "ARG_IG_VieMaxPlus" }},
    {"Alw_Projectile_Rayman_model", { "YLT_PoingInit", "YLT_Shoot", "BNT_PoingGrappin", "BNT_PoingGrappinInit", "FRD_GrappinBisInit", "FRD_GrappinBisOnMeTire", "FRD_GrappinBisTireObjet", "FRD_GrappinBisFin" }},
    {"CHG_TexteMenu", { "FRH_text_init", "DS1_text_fadein", "DS1_text_fadeout", "STN_Texte" }},
    {"ARG_FondMenu", { "DS1_FondMenu1Standard" }},
    {"YAM_LumsCurseur", { "YAM_LumsCurseur1Standard", "YAM_LumsCurseur0Init" }},
    {"Alw_Faisceau_Model", { "OLD_faisceau_init", "OLD_faisceau_normal", "OLD_faisceau_fin", "OLD_faisceau_accessoire" }},
    {"DS1_OneShot", { "DS1_InitSoundOiseau2", "DS1_StartOiseau2", "DS1_InitSoundOiseau1", "DS1_StartOiseau1", "DS1_InitSoundOiseau4", "DS1_StartOiseau4", "DS1_InitSoundOiseau3", "DS1_StartOiseau3", "DS1_InitSoundCrapeau", "DS1_StartCrapaud", "DS1_InitSoundBulles", "DS1_InitSoundCave2", "DS1_InitSoundSonar", "DS1_StartSonar", "DS1_InitSoundGroutgrot", "DS1_StartGroutgrot", "DS1_InitSoundBeurk", "DS1_InitSoundMouette", "DS1_StartMouette", "DS1_InitSoundVagues", "DS1_StartVagues", "DS1_InitSoundUnderB", "DS1_StartUnderB", "DS1_StartBeurk", "DS1_StartBulles", "DS1_StartCave2", "DS1_InitSoundOiseau5", "DS1_StartOiseau5", "DS1_InitSoundHibou", "DS1_StartHibou", "DS1_InitSoundPtitBul", "DS1_StartSoundPtitBul", "DS1_InitSoundOrage", "DS1_StartOrage", "DS1_InitSoundEpave", "DS1_StartEpave", "DS1_InitSoundPeurIntro", "DS1_StartPeurIntro" }},
    {"LevelAstro_10", { "YLT_InitLevel" }},
    {"MIC_Tir_Starwars", { "MIC_TSW_INIT", "MIC_TSW_Tire", "MIC_TSW_FinDuTir", "MIC_TSW_Delai" }},
    {"ARG_SerieRouge", { "ARG_LR_Init", "ARG_LR_WaitRM" }},
    {"ARG_SerieLums", { "ARG_SR_Init", "ARG_SR_PrepareLums", "ARG_SR_AttendSignal", "ARG_SR_DecompteTemps" }},
    {"MIC_EclaboussuresObus", { "MIC_Eclab_INIT", "MIC_Eclab_Surveille" }},
    {"ARG_Rayseau", { "ARG_Init", "ARG_ChoixMoyenTransport", "ARG_ChoixDestination", "ARG_VaAuWaypoint", "ARG_VaEnSautant", "ARG_RmEnSaut", "ARG_Atterrit", "ARG_RmTombe", "ARG_RmFini", "ARG_VaEnGlissant", "ARG_AttendSol", "ARG_VaAspire", "ARG_VaEnNageant", "DS1_Pause" }},
    {"LevelBall", { "YLT_InitLevel", "MIC_LBall_Loop", "YGE_Fade" }},
    {"OLD_francesco", { "OLD_franc_init", "OLD_franc_voyage", "ARG_Franc_Attend" }},
    {"ARG_DebutDeMap", { "ARG_Deb_Init", "ARG_Deb_Attend", "ARG_Deb_Vide", "ARG_GoToRezo", "ARG_SkipRezo", "ARG_Seconde_Entree" }},
    {"Alw_Plouf_Model", { "SUN_Plouf_Init", "SUN_Alw_Sillage", "SUN_Alw_Gerbe", "FRH_rond_seul", "FRH_rond_multiple" }},
    {"MOM_Ray_Bast10", { "MOM_Ray_Bast10_init", "MOM_Ray_Bast10_THX" }},
    {"LevelBast_09", { "YLT_InitLevel", "YGE_Fade", "YGE_Fin" }},
    {"STN_cam_pluie", { "STN_pluie_init", "VIM_pluie_fixe", "VIM_pluie_oriente" }},
    {"STN_Sofkipleu", { "STN_Sofkipleu_init", "STN_Sofkipleu_detect_in", "STN_Sofkipleu_fade_in", "STN_Sofkipleu_detect_out", "STN_Sofkipleu_fade_out" }},
    {"MOM_pirate_sbire_cine_2", { "MOM_sbire_init", "MOM_sbire_THX_move" }},
    {"THX_BlaBla", { "SUN_Blabla_Init", "SUN_Blabla_Relax", "SUN_Blabla_THX" }},
    {"OLD_THX", { "SUN_thx_init", "SUN_thx_fin", "SUN_thx_attend", "SUN_thx_parle", "SUN_thx_rencontre", "SUN_Thx_Cine", "SUN_Thx_Rien", "SUN_Thx_Sans_THX", "SUN_THX_Attendbouton" }},
    {"MOM_porteCine_bast10", { "MOM_porteCine_init", "MOM_porteCine_THX" }},
    {"FRH_sbire_gnak", { "FRH_gn_init", "FRH_gn_deplace_init", "FRH_gn_deplace_capa", "FRH_gn_deplace_impossible", "FRH_gn_deplace_next", "FRH_gn_choix_action", "FRH_gn_crochet", "FRH_gn_saute", "FRH_gn_shoot", "FRH_gn_insert", "FRH_gn_mort", "FRH_gn_to_lance", "FRH_gn_to_tourne", "FRH_gn_to_surveil", "FRH_gn_courir", "FRH_gn_avant_detection", "FRH_gn_chute_inf" }},
    {"LevelBast_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"CHR_Porte", { "CHR_InitPorte", "CHR_AttendGenere", "ARG_FiniPorte", "ARG_Aspiration", "ARG_Init_OnlyCB28", "ARG_OnlyCB28_Main", "DS1_DialOne", "DS1_Dial_Next", "DS1_dial_ok", "DS1_ApparitionTexte", "DS1_ByePorte", "DS1_PorteGlob20" }},
    {"OLP_PlotKiTombe", { "MIC_Plot_INIT", "MIC_Plot_SEnfonce", "MIC_Plot_Interrupteur_On", "MIC_Plot_Aller", "MIC_Plot_Retour", "MIC_Plot_Interrupteur_Off" }},
    {"SUN_PosCam_Smooth", { "SUN_CamSmooth_Init", "SUN_CamSmooth_Normal" }},
    {"OLP_Switch_Auto", { "OLP_Init_Switch", "OLP_Attente_switch", "OLP_MI_switch" }},
    {"SUN_PosCam_Cut", { "SUN_CamCut_Init", "SUN_CamCut_Normal", "SUN_CamCut_Dedans", "CHR_RetourNormal" }},
    {"MIC_GorilleGardien", { "MIC_Gege_INIT", "MIC_Gege_Surveille", "MIC_Gege_Charge", "MIC_Gege_Repart", "MIC_Gege_TourneSurPlace", "MIC_Gege_Chute", "MIC_Gege_Pietine", "MIC_Gege_Prune", "MIC_Gege_Electrique", "MIC_Gege_Pause", "MIC_Gege_RepartReseau", "MIC_Gege_Delai", "MIC_Gege_OnMeTaquine", "MIC_Gege_PasCompris" }},
    {"BNT_EnferDeDante", { "BNT_Comport_InitDante", "MIC_Comport_Flamme" }},
    {"CHR_CheckP", { "CHR_check_init", "CHR_check_test", "CHR_check_actif", "STN_check_boucleAOJ", "STN_check_debutAOJ", "STN_check_finAOJ" }},
    {"VCT_GenPrune", { "VCT_GenPrune_AttenteSansPrune", "VCT_GenPrune_AttenteAvecPrune" }},
    {"OLD_SBIRE_shoot_sol", { "SUN_SB_shoot_init", "SUN_SB_shoot_attentesol_av_detection", "SUN_SB_shoot_attaq_enjoue", "SUN_SB_shoot_attaq_shoot", "SUN_SB_shoot_Cpaf", "SUN_SB_shoot_CParachute", "SUN_SB_shoot_Cattend", "SUN_SB_shoot_mort", "SUN_SB_shoot_insert", "SUN_SB_shoot_crochet", "SUN_SB_shoot_chute", "SUN_SB_shoot_saut_impul", "SUN_SB_Shoot_saut_go", "SUN_SB_shoot_chute_oriente", "OLD_SB_shoot_Sleeping", "FRH_SB_shoot_reveil" }},
    {"STN_SaveSwitch", { "STN_SaveSwitch_init", "STN_SaveSwitch_check", "DS1_TempsMusique" }},
    {"JEZ_lumiere", { "JEZ_MIC_Loupiottes_INIT", "JEZ_MIC_Loupiottes_Surveille", "DS1_PasseLaPommade", "DS1_CestFini", "DS1_VerificationGenerale", "DS1_NextStep", "DS1_WaitForSchmurchz" }},
    {"MIC_fleche_helpeuse", { "MIC_FlecheH_INIT", "MIC_FlecheH_Allumee", "MIC_FlecheH_Eteinte", "MIC_FlecheH_Allumee_Etat", "MIC_FlecheH_Eteinte_Etat" }},
    {"STH_teleport", { "STH_teleport_init", "ARG_Teleport_Tableau", "STH_teleport_detect", "STH_teleport_attente", "STH_teleport_intermediaire", "SUN_PirouliPiroula" }},
    {"SDZ_SteleAOJ", { "SDZ_Stele_0_Init", "SDZ_Stele_1_Resume", "SDZ_Stele_2_Resume_FadeIn", "SDZ_Stele_3_Resume_Attente", "SDZ_Stele_4_Resume_FadeOut", "SDZ_Stele_5_Attente", "SDZ_Stele_6_Resume_AttenteBouton" }},
    {"YAM_PastilleVersLaMapMonde", { "YAM_Pastille1Normal", "YAM_Pastille2Active", "ARG_Aspirale", "ARG_Apparition", "ARG_PastilleAttendSol", "ARG_WaitChangeMap", "DS1_Inerte" }},
    {"JCP_dead_perso", { "JCP_init_dead", "YLT_Wait" }},
    {"MIC_GenCamera", { "MIC_GenCamera_INIT", "MIC_GenCamera_Attend", "MIC_GenCamera_Filme", "MIC_GenCamera_AttendCB28", "MIC_GenCamera_FilmeCb28" }},
    {"IVN_DebutDeMap", { "IVN_Deb_Init", "IVN_Deb_Attend", "IVN_Deb_Vide", "IVN_GoToRezo" }},
    {"DS1_SonBast10", { "DS1_CrapeauB10_Init", "DS1_CrapaudB10_Start", "DS1_BebetesB10_Init", "DS1_BebetesB10_Start", "DS1_HibouB10_Init", "DS1_HibouB10_Start", "DS1_VentBouclantB10", "DS1_NuitAmbianceB10", "DS1_OrageDebutB10", "DS1_FlammecheB10", "DS1_SonMoulinB10_Init", "DS1_SurfaceSonMoulinB10", "DS1_TestFinSonMoulinB10" }},
    {"OLD_ptitchampi", { "OLD_champi_init", "OLD_champi_normal" }},
    {"ARG_Papillon", { "ARG_Pinit", "ARG_PattendRM", "ARG_Pdecolle" }},
    {"STN_kipik", { "STN_kipik_init", "STN_kipik_pozzz", "STN_kipik_bouzzz", "STN_kipik_kassoszzz" }},
    {"STH_controleSC", { "STH_controleSC_init", "STH_controleSC_main", "STH_controleSC_Suivant", "STH_controleSC_comptage" }},
    {"IVN_poisson_drole", { "IVN_drole_init", "IVN_drole_normal2", "IVN_drole_retour", "IVN_drole_normal3" }},
    {"ARG_NageDevantRM", { "ARG_P01_init", "ARG_P02_CheckPos", "ARG_P03_Go", "ARG_P04_Fuit", "ARG_P05_Retour", "ARG_P06_Saute", "ARG_P07_AttenteRandom" }},
    {"JEZ_LeMoulin", { "JEZ_moulin_init", "JEZ_moulin_tourne" }},
    {"JEZ_plateHelice", { "JEZ_platehelice_init", "JEZ_platehelice_detecte", "JEZ_platehelice_up", "JEZ_platehelice_turndown", "JEZ_platehelice_turnup", "JEZ_platehelice_down", "DS1_DetecteRay", "DS1_DemarreVoyage", "DS1_JyVais", "DS1_JeSuisArrive", "DS1_JeMeRetourne", "DS1_JeReparsDanslAutreSens", "DS1_ImBack", "DS1_JeMeRemetAlEndroit" }},
    {"OLD_alw_tonneau_model", { "OLD_alw_tonneau_init", "OLD_alw_tonneau_vol" }},
    {"BNT_ThePrune", { "BNT_PruneInit", "BNT_PruneColleEtReste", "BNT_PrunePortee", "BNT_Comport_PruneQuiFlotte", "DS1_PruneEnchutePlum", "DS1_PruneEnChuteLearn", "DS1_PruneQuiFlotteRayDessus", "DS1_JeDisparais", "DS1_PruneChuteMineBast", "DS1_PruneEnChutePlum10" }},
    {"SUN_basic", { "SUN_init", "FRH_Mic_target", "OLD_tournant", "OLD_tete_chercheuse", "OLD_toutdroit_en_tournant", "OLD_toutdroit" }},
    {"LevelBast_20", { "YLT_InitLevel" }},
    {"OLP_PorteLaser_Switch", { "OLP_Init_PorteLaser", "OLP_Fermeture", "OLP_Ouverture", "OLP_Fermee", "OLP_Ouverte" }},
    {"CEB_porte_bois", { "CEB_init", "CEB_attente_eclatement", "CEB_eclatement_porte" }},
    {"STN_sparadrap_metal", { "STN_Sparametal_init", "STN_Sparametal_detection", "STN_Sparametal_explose" }},
    {"SUN_Tono_Generator", { "SUN_Trap_Init", "SUN_Trap_Normal" }},
    {"BNT_TonneauFusee", { "BNT_Init", "BNT_EnChuteLibre", "BNT_TonneauDragsterAerien", "BNT_TonneauPorte", "SUN_permiere_chute", "MIC_Tono_Ramassable", "MIC_Init_Generateur", "MIC_Tono_Type1_Fin", "MIC_Tono_Type1_Debut" }},
    {"ARG_CageLums", { "ARG_CageInit", "ARG_AttendOuverture", "ARG_GenereLums", "ARG_FiniDePondre", "ARG_PafEnLair", "ARG_Unseen", "ARG_PutainCestBuggeLesMacros", "DS1_EmploiTempsCetaitBien" }},
    {"MIC_BancDePiranhas_NoCollision", { "MIC_BancPir_NC_INIT", "MIC_BancPir_NC_Surveille", "MIC_BancPir_NC_Fini" }},
    {"MIC_sparadrap", { "MIC_Sparadrap_INIT", "MIC_Sparadrap_AttendPaf", "MIC_Sparadrap_Zouip", "MIC_Sparadrap_RemetLaZique" }},
    {"MIC_PiranhaSauteurVisible", { "MIC_PSV_INIT", "MIC_PSV_Synchro", "MIC_PSV_SautDebut", "MIC_PSV_SautTop", "MIC_PSV_SautPlouf", "MIC_PSV_SautFin", "MIC_PSV_Delai", "MIC_PSV_Tourne", "MIC_PSV_AvantSaut", "MIC_PSV_FaisDodo", "MIC_PSV_Paf", "MIC_PSV_Fini" }},
    {"MIC_BoiteDisco", { "MIC_BoiteDisco_INIT", "MIC_BoiteDisco_Tourne", "MIC_BoiteDisco_Off" }},
    {"GRP_Trampoline", { "GRP_Init" }},
    {"STN_pontlevis", { "STN_pontlevis_init", "STN_pontlevis_open", "STN_pontlevis_close", "JAC_pontlevis_Attends_Fermeture", "JAC_pontlevis_Attends_Ouverture" }},
    {"OLP_Inverseur", { "OLP_Init_Inverseur", "OLP_1_Sbire", "OLP_2_Sbires", "OLP_Rien" }},
    {"DS1_RegleurInertie", { "DS1_RegleurInertie_Init", "DS1_Inertie_TestPresenceRayman", "DS1_Inertie_RaymanOut" }},
    {"SDZ_MurfyAOJ", { "SDZ_AOJ_0_Init", "SDZ_AOJ_1_Attente", "SDZ_AOJ_2_Approche", "SDZ_AOJ_3_Parle", "SDZ_AOJ_4_Sortie", "SDZ_AOJ_5_Resume", "SDZ_AOJ_6_Resume_FadeIn", "SDZ_AOJ_7_Resume_Attente", "SDZ_AOJ_8_Resume_FadeOut", "SDZ_AOJ_9_Tourne", "SDZ_AOJ_A_ParleAttendBouton" }},
    {"OLP_IA_bzzz_IA", { "OLP_Ini_IA_bzzz_IA", "OLP_A_toi" }},
    {"OLP_DetruitCamera", { "OLP_Init_DetruitCamera", "OLP_Attente_DetruitCamera" }},
    {"OLP_Gendoor_Detruit_Tonneau_R40", { "OLP_Init_Detruit_Tonneau", "OLP_VasyDetruit" }},
    {"IVN_Simple_Granouil", { "IVN_init_granouil", "IVN_saut_granouil", "IVN_attente_granouil", "DS1_init_CB_granouil" }},
    {"OLD_fumee_toxique", { "OLD_fumee_toxiq_init", "OLD_fumee_toxiq_simple", "OLD_fumee_toxiq_multiple" }},
    {"STH_petitspiranha_deco", { "STH_piti_init" }},
    {"Alw_Feu_model", { "SUN_Alw_Feu_Init", "SUN_Alw_Feu_Boule", "SUN_Alw_Feu_Jet", "OLD_alw_feu_boule_queue", "OLD_alw_feu_croix_feu", "DS1_Alw_Feu_Jet_temps", "CHR_basic_flamme", "OLD_feu_boule_no_ZdEM", "OLD_feu_boule_boss" }},
    {"LevelBast_22", { "YLT_InitLevel" }},
    {"STN_bombginreita", { "STN_bombginreita_init", "STN_bombginreita_genere", "STN_bombginreita_detecte" }},
    {"OLP_Nuages_Generateur_Model", { "OLP_Nuages_Generateur_init", "OLP_Nuages_Generateur_normal", "OLP_Nuages_Generateur_action", "OLP_Nuages_Generateur_creation", "DS1_Nuages_par_intermittence" }},
    {"IVP_Foudre", { "DS1_arc_init" }},
    {"FRD_EntreDeux", { "FRD_TesteCollisionCorridor", "FRD_TesteSortieCorridor" }},
    {"MOM_missileCine", { "MOM_missileCine_init", "MOM_missileCine_THX" }},
    {"MIC_LanceBanane", { "MIC_LB_INIT", "MIC_LB_Surveille" }},
    {"SDZ_Ly_Cine", { "SDZ_LyCine_Init", "SDZ_LyCine_Vol", "SDZ_LyCine_Normal" }},
    {"SDZ_RayDum", { "SDZ_Dum_0_Init", "SDZ_Dum_1_THX", "SDZ_Dum_2_Course", "SDZ_R40Dum_0_Init", "SDZ_R40Dum_1_THX", "SDZ_Dum_1_Normal" }},
    {"SUN_Lums_Cinema", { "SUN_Lums_Init", "SUN_Lums_THX" }},
    {"SDZ_FX_Bast20", { "SDZ_FX_0_Init", "SDZ_FX_1_Normal", "DS1_FX_2_THX", "SDZ_FX_3_WaitBoom" }},
    {"OLP_Timing_Active_Aide", { "OLP_Init_Timing_Active", "OLP_Compte_Active", "OLP_En_Marche" }},
    {"BNT_grappinable", { "PHL_Lums_Init", "ARG_Type2_ParcoursBoucle", "ARG_Type3", "JCP_type_lums_v", "JCP_vers_wp_rm", "JCP_retourne", "CHR_vers_wp_init", "PHL_Attends_a_dest", "ARG_Type1_Immobile", "ARG_LibereDeLaCage", "ARG_Libre" }},
    {"Alw_Bombe_Model", { "SUN_Bmb_Heli_Init", "SUN_Bmb_Heli_Detec", "OLD_bmb_heli_vol2", "YLT_Vol", "YLT_Vibre", "YLT_DetruitBomb" }},
    {"LevelBatam_10", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"MOM_batam_cine", { "MOM_bateauAmiralCine_init", "MOM_bateauAmiralCine_THX" }},
    {"SUN_Pir_Barbu_Cinema", { "SUN_Pir_Barb_Cine_Init", "SUN_Pir_Barb_Cine_THX" }},
    {"SUN_Pir_Chaise_Cine", { "MOM_pirChaise_Cine_init", "MOM_pirChaise_Cine_THX" }},
    {"SUN_Pir_Lun_Cinema", { "SUN_Pir_Lun_Cine_Init", "SUN_Pir_Lun_Cine_THX" }},
    {"NIK_Nef_Cine_THX", { "NIK_Nef_Cine_init", "NIK_Nef_Cine_THX" }},
    {"MOM_Ray_bat10", { "MOM_Ray_bat10_init", "MOM_Ray_bat10_THX" }},
    {"YAM_GenCompteurCine", { "YAM_GenCompteurCine0Init", "YAM_GencompteurCine1Cine", "YAM_GenCompteurCine2CineFin", "MOM_GenCompteurCine2CineFin2" }},
    {"SUN_CamAnim_THX", { "SUN_CamAnim_Init", "SUN_CamAnim_THX" }},
    {"NIK_GEN_NIK", { "NIK_Batam_10", "NIK_Init" }},
    {"SDZ_Porte_Cine", { "SDZ_Porte_0_Init", "SDZ_Porte_1_THX" }},
    {"LevelBatam_20", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"THX_Spielberg", { "SDZ_THX2_init", "SDZ_THX2_fin", "SDZ_THX2_attendWP", "SDZ_THX2_parle", "SDZ_THX2_AttendCB28", "SDZ_THX2_Sans_THX" }},
    {"SDZ_SpecialFX", { "SDZ_sfx_0Init", "SDZ_sfx_1Normal", "SDZ_sfx_3Bulle" }},
    {"SDZ_General_Cine", { "SDZ_General_0Init", "SDZ_General_1Normal" }},
    {"SDZ_Coffre_Cine", { "SDZ_Coffre_0_Init", "SDZ_Coffre_1_THX" }},
    {"SDZ_Rhoppy", { "SDZ_Rhop_0_Init", "SDZ_Rhop_1_THX" }},
    {"IVN_simple_bat", { "IVN_chov_base", "IVN_chov_tombe", "IVN_chov_vol", "DS1_chov_init_cb" }},
    {"YLT_Actor_Model1", { "YLT_pl_explo_init" }},
    {"Levelboat01", { "YLT_InitLevel" }},
    {"OLD_helice", { "OLD_helice_init", "OLD_helice_tourne" }},
    {"ECO_au_revoir_rayman", { "ECO_init", "ECO_transparence", "ECO_suspense", "ECO_changemap", "ECO_transparence_bis" }},
    {"Levelboat02", { "YLT_InitLevel" }},
    {"FRH_tremplin", { "FRH_tr_init", "FRH_tr_move" }},
    {"SUN_Barriere_Laser", { "SUN_BarriereLaser_Init", "SUN_BarriereLaser_Normal", "SUN_BarriereLaser_Inter" }},
    {"SDZ_Wind", { "SDZ_Wind_0_Init", "SDZ_Wind_1_Normal", "SDZ_Wind_2_Souffle" }},
    {"Alw_Fumee_model", { "SUN_Nuage_init", "SUN_pluie", "SUN_fumee_go" }},
    {"OLD_alphabet", { "OLD_alphab_init" }},
    {"Levelbonux", { "YLT_InitLevel", "MIC_World_Titre", "MIC_World_Infos", "MIC_World_TesteFin", "MIC_World_Fin", "MIC_World_Recompenses", "MIC_World_AjouteVie", "MIC_World_AjouteShoot", "MIC_World_AfficheRay", "MIC_World_ToTheMapMonde", "MIC_World_SansInfos", "MIC_World_Bravo", "MIC_World_Menu", "MIC_World_RelacheStartBordel" }},
    {"MIC_Bebe_Bonux", { "MIC_bbb_INIT", "MIC_bbCourse_Avance", "MIC_bbCourse_Saut", "MIC_bbCourse_NouvoWp", "MIC_bbCourse_Coule", "MIC_bbCourse_FaitCoucou", "MIC_bbCourse_Fin" }},
    {"MIC_CameraCircuit", { "MIC_CC_INIT", "MIC_CC_NouvoWp", "MIC_CC_Oriente", "MIC_CC_FixeSuivi", "MIC_CC_Fixe", "MIC_CC_DeuxActeurs", "MIC_CC_Classique" }},
    {"MIC_LunetteBonux", { "MIC_Spex_INIT", "MIC_Spex_NouvoWp", "MIC_Spex_Avance", "MIC_Spex_Saut", "MIC_Spex_Bomber", "MIC_Spex_Trebuche", "MIC_Spex_Fin" }},
    {"MIC_LudiBonux", { "MIC_Ludi_INIT", "MIC_Ludi_DonneKado", "MIC_Ludi_SeSauve", "MIC_Ludi_Delai" }},
    {"OLD_bebe_globox", { "OLD_bb_globox_init", "OLD_bb_globox_normal" }},
    {"levelCask_10", { "ZOR_INITLevel", "ZOR_LevelLoop", "ZOR_ZeBest" }},
    {"SUN_Cam_AxeForce", { "SUN_AxeForce_Init", "SUN_AxeForce_Axe", "SUN_Axeforce_Nebulus", "OLD_axeforce_nebulus_targetcible" }},
    {"MIC_GerbeTonneau", { "MIC_GerbeTonneau_INIT", "MIC_GerbeTonneau_Teste", "MIC_GerbeTonneau_Fini" }},
    {"MIC_ZigouillateurNPersos", { "MIC_ZNP_INIT", "MIC_ZNP_Zigouille", "MIC_ZNP_Distance", "MIC_ZNP_CB28", "MIC_ZNP_Etat", "MIC_ZNP_Destruction" }},
    {"MIC_ActivateurMultiple", { "MIC_ActivMul_INIT", "MIC_ActivMul_SurveilleDistance", "MIC_ActivMul_SurveilleEtatRay", "MIC_ActivMul_SurveilleCB28" }},
    {"GRP_GratificationAnim", { "MIC_INIT", "GRP_FinSon", "MIC_Fini", "MIC_Detection_CB28", "MIC_Detection_Distance", "GRP_Detection_Mort", "DS1_RayDanseAuSol", "DS1_YeahYeahYeah", "DS1_FreeStyle" }},
    {"STN_planches", { "STN_planche_init", "STN_planche_crack", "STN_planche_detruite_poutre", "STN_planche_explose", "STN_planche_suivante", "STN_planche_tremble", "STN_planche_tremble_init", "STN_planche_detruite_non_poutre", "STN_planche_switch" }},
    {"LevelCask_30", { "YLT_InitLevel", "DS1_LevelLoop" }},
    {"MIC_StarTrek", { "MIC_StarTrek_INIT", "MIC_StarTrek_SurveilleSpok", "MIC_StarTrek_Interrupteur" }},
    {"MIC_GrilleInterruptee", { "MIC_GrilleInt_INIT", "MIC_GrilleInt_Attend", "MIC_GrilleInt_Monte", "MIC_GrilleInt_Descend", "ARG_GrilleInt_Pause" }},
    {"MIC_Killeur", { "MIC_Killeur_INIT", "MIC_Killeur_Surveille" }},
    {"STN_batokipass", { "STN_batokipass_init", "STN_batokipass_chemin" }},
    {"ARG_Ptizetre", { "ARG_PTinit", "ARG_PTattend", "ARG_PTsortcage", "ARG_PTvaWp", "ARG_PThello", "ARG_PTsautmonte", "ARG_PTsautdescend", "ARG_PTprepare", "DS1_PTdanse", "ARG_PTsautFinalmonte", "ARG_PTsautFinaldescend", "ARG_PTouvrePorte", "DS1_PTdanseFin" }},
    {"STN_varappe", { "STN_varap_init", "STN_varap_detecte", "STN_varap_tremble_init", "STN_varap_chute", "STN_varap_detruit", "STN_varap_tremble" }},
    {"Alw_Projectile_model", { "CHR_init", "CHR_go", "DS1_GoSpecialNav", "JAC_mort" }},
    {"LevelChase_10", { "YLT_InitLevel", "DS1_Leveloop" }},
    {"STN_bato", { "STN_bato_init", "STN_bato_vitesse_ray", "STN_bato_vitesse_fixe", "STN_bato_fantome" }},
    {"STN_genbato", { "STN_genbato_init", "STN_genbato_bombe", "STN_genbato_boulet", "STN_genbato_menu", "STN_genbato_suivant", "STN_genbato_surprise", "STN_genbato_vitesse", "STN_genbato_boul_ray", "STN_genbato_fantome" }},
    {"OLD_pouletzombie", { "OLD_poulzomb_init", "OLD_poulzomb_voyage", "OLD_poulzomb_mort", "OLD_poulzomb_visible", "OLD_pz_sort", "OLD_pz_traverse", "OLD_pz_init", "SUN_poulzomb_retour", "DS1_Poulet_Depart_Reseau" }},
    {"DS1_PastilleAPeage", { "DS1_Aspirale", "DS1_PastilleInit", "DS1_PastilleInerte" }},
    {"DS1_ZyvaEnvoieTesLums", { "DS1_InitCompteur", "DS1_compteur_attente", "DS1_compteur_Reattente", "DS1_compteur_attente_Nego10", "SDZ_CompteurFadeIn", "SDZ_CompteurAttenteBouton", "SDZ_CompteurFadeOut" }},
    {"DS1_Ly_Potiche", { "DS1_Init_Potiche", "DS1_Ly_Potiche_OnduleTonCorps" }},
    {"OLD_tonneau_reseau", { "OLD_ton_reseau_arret", "OLD_ton_reseau_init", "OLD_ton_reseau_voyage", "OLD_ton_reseau_chute", "STN_ton_reseau_coule", "DS1_ton_reseau_monte" }},
    {"OLD_ponton", { "OLD_ponton_init", "OLD_ponton_normal", "GRP_WaitPourRepositionnement", "IVN_ponton_void" }},
    {"MIC_PasserelleMarais", { "MIC_Pass_INIT", "MIC_Pass_Tombe", "STN_Pass_tremble", "MIC_Pass_Tzoing", "MIC_pass_detruit", "STN_pass_attend" }},
    {"STN_bato_boulet", { "STN_boulet_init", "STN_boulet_tir", "STN_boulet_boum" }},
    {"STN_boulet_surprise", { "STN_boulet_surprise_init", "STN_boulet_surprise_tir", "STN_boulet_surprise_boum" }},
    {"DS1_Missile_direct", { "DS1_Missile_direct_init", "DS1_missile_direct_attaque" }},
    {"DS1_Missile_Chrono", { "DS1_Missile_Chrono_Init", "DS1_missile_chrono_attaque" }},
    {"LevelChase_22", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"ARG_SimpleSbire", { "ARG_Init", "ARG_Tirs", "ARG_AttendRM", "ARG_Paf", "ARG_Meurt", "DS1_Poing" }},
    {"ARG_Gen_Tono_Roule", { "ARG_GTR_Init", "ARG_GTR_Attend", "ARG_GTR_Go" }},
    {"SUN_Damocles", { "SUN_Damocles_Init", "SUN_Damocles_Normal" }},
    {"ARG_Tonneau_DonkeyKong", { "ARG_TDK_Init", "ARG_TDK_main", "ARG_TDK_Prepare", "ARG_TDK_AttendWP" }},
    {"LevelEarth_10", { "CHG_WorldLoop", "BNT_InitGameWorld" }},
    {"ARG_Chenille_Reseau", { "ARG_Initial", "ARG_Principal", "ARG_MarcheOuCreve", "ARG_SautDeb", "ARG_Marche", "ARG_Attaque", "ARG_Restart" }},
    {"MIC_PiranhaHaineux", { "MIC_PirHar_INIT", "MIC_PirHar_Debut", "MIC_PirHar_Saute", "MIC_PirHar_Explose" }},
    {"OLD_SBIRE_alarme", { "OLD_SBIRE_alarme_init", "OLD_SBIRE_alarme_Cpaf", "OLD_SBIRE_alarme_mort", "OLD_SBIRE_alarme_init_chemin", "OLD_SBIRE_alarme_recherche", "OLD_SBIRE_alarme_balade", "OLD_SBIRE_alarme_saut", "OLD_SBIRE_alarme_attente", "OLD_SBIRE_alarme_surRM", "OLD_SBIRE_alarme_crochet", "OLD_SBIRE_alarme_choix_arme", "OLD_SBIRE_alarme_shoot", "OLD_SBIRE_alarme_en_joue", "OLD_SBIRE_alarme_sleeping", "FRH_SBIRE_alarme_returnWP", "FRH_SBIRE_alarme_att_RM", "DS1_SBIRE_alarme_wait", "DS1_Sbire_Alarme_changement", "DS1_SBIRE_alarme_Cpaf_air" }},
    {"MIC_OctusDiabolus", { "MIC_OD_INIT", "MIC_OD_Ptoing" }},
    {"MIC_MaturinDesMarais", { "MIC_Maturin_INIT", "MIC_Maturin_Sortie", "MIC_Maturin_Slurp", "MIC_Maturin_Bouffe" }},
    {"LevelEarth_20", { "YLT_InitLevel", "YLT_LevelLoop", "ZOR_PlateForme" }},
    {"SUN_Cam_Suivi", { "SUN_Suivi_init", "SUN_suivi_go" }},
    {"SUN_BouchaFeu", { "SUN_BouchaFeu_Init", "SUN_BouchaFeu_Cycle", "SUN_BouchaFeu_Inter" }},
    {"SUN_Interrupteurs", { "SUN_INT_Rich_Init", "SUN_INT_Rich_Minut", "SUN_INT_Rich_Normal", "SUN_INTER_Init", "SUN_INT_Pov_Init", "SUN_INT_Pov_Normal" }},
    {"SUN_Mur_Ronce", { "SUN_Mur_Init", "SUN_Mur_Attente", "SUN_Mur_Inactif" }},
    {"IVP_ActiveTunnel", { "IVP_Init_tunnel" }},
    {"IVP_Plateforme", { "IVP_init", "IVP_voyage", "IVP_disparait", "IVP_arret", "IVP_apparait", "ARG_AttendStart", "DS1_Restart", "DS1_Voyage_Seul", "DS1_WaitAndSee" }},
    {"OLD_mur_a_eclater", { "OLD_mur_init", "OLD_mur_coup1", "OLD_mur_coup2", "OLD_mur_coup3", "DS1_WaitForImpact" }},
    {"SUN_Porte_Simple", { "SUN_PorteS_Init", "SUN_PorteS_Normal", "SUN_PorteS_Ouverte", "SUN_PorteS_Ferme", "DS1_PorteS_Monte", "DS1_Porte_TempoSommet" }},
    {"SUN_PLF_Plate", { "SUN_PLF_Plate_Init", "SUN_PLF_Plate_Normal", "SUN_PLF_Plate_Avance", "SUN_PLF_Plate_Retour", "SUN_PLF_Plate_Normal2", "SUN_PLF_Plate_Avance2", "SUN_PLF_Plate_Retour2", "IVP_avance", "IVP_recule", "IVP_normal", "IVP_init" }},
    {"SUN_PLF_Pilier", { "SUN_PLF_Pilier_Init", "SUN_PLF_Pilier_Normal", "SUN_PLF_Pilier_Tombe", "SUN_PLF_Pilier_Tombe2", "SUN_PLF_Pilier_Tombe3", "SUN_PLF_Pilier_Monte3", "IVP_remonte", "DS1_Tombe2_testRemonte", "DS1_Tombe_TestFinal", "DS1_SUN_PLF_Pilier_Test_Monte3" }},
    {"SUN_PtiteRonce", { "SUN_Ronce_Init", "SUN_Ronce_Sortie", "SUN_Ronce_Normal", "DS1_JaiPrisGras", "SUN_Ronce_Attente", "SUN_Ronce_Attente2" }},
    {"LevelEarth_30", { "YLT_InitLevel", "ZOR_LevelLoop", "ZOR_ModeLook" }},
    {"STN_Spoutz_generator", { "STN_spoutz_generator_init", "STN_spoutz_generator_detecte", "STN_spoutz_generator_genere", "STN_spoutz_generator_interrupteur", "STN_spoutz_generator_zone" }},
    {"OLD_coulee_lave", { "OLD_coul_lav_init", "OLD_coul_lav_normal", "ODA_coul_lav_testcollision" }},
    {"MIC_MurKiBouge", { "MIC_MKB_INIT", "MIC_MKB_Dehors", "MIC_MKB_Rentre", "MIC_MKB_Dedans", "MIC_MKB_Sort" }},
    {"SUN_Porte_Terre", { "SUN_Porte_Init", "SUN_Porte_Normal", "SUN_Porte_Ouvre", "DS1_Porte_Attend", "DS1_Porte_TempoOuverte" }},
    {"OLD_tterre_colon_pivot", { "OLD_t_colon_pivot_init", "SUN_t_colon_pivot_normal" }},
    {"OLD_t_petite_colon", { "OLD_t_petit_colon_init", "OLD_t_petit_colon_normal" }},
    {"OLD_flaque_plouf_lave", { "OLD_plouf_lave_init", "OLD_plouf_lave_fin" }},
    {"STN_kapoueh", { "STN_kapoueh_init", "STN_kapoueh_detecte", "STN_kapoueh_fonce" }},
    {"levelEnd_10", { "CHG_WorldLoop", "BNT_InitGameWorld" }},
    {"SDZ_RayPlik", { "SDZ_Dum_0_Init", "SDZ_Dum_1_THX", "SDZ_Dum_2_Fin" }},
    {"OLP_Interrupteur_Modele1", { "OLP_Init_Interrupteur", "OLP_Debut_Interrupteur", "OLP_Temps_Interrupteur", "CEB_interrupteur_simple", "ARG_UneSeuleFois_init", "ARG_ShootParDevant", "ARG_ShootDerriere" }},
    {"OLD_mas_broken", { "OLD_mas_init", "OLD_mas_tombe", "OLD_mas_parterre", "OLP_AttendTombe" }},
    {"ARG_Tremble", { "ARG_Init", "ARG_AttendSignal", "ARG_Tremblement" }},
    {"OLP_PlanteMorph_Modele1", { "OLP_Init_PlanteMorph", "OLP_Debut_PlanteMorph", "ARG_vide", "ARG_AttenteSynchro" }},
    {"MIC_FlammeGlobosk", { "MIC_FlamG_INIT", "MIC_FlamG_AttendGlobosk", "MIC_FlamG_JeVaisMEtteindre", "MIC_FlamG_Disparait" }},
    {"ARG_AttaqueGlobox", { "ARG_Init", "ARG_RegardeSiPeur", "ARG_RegardeSiPasPeur" }},
    {"ARG_SansVie", { "ARG_Init", "ARG_Fightingable", "ARG_SpecialFleche", "ARG_SpecialSortie2", "DS1_FightingableType0", "DS1_SpecialFlecheSuite", "DS1_SpecialSortie2Suite", "DS1_Billy_Bob" }},
    {"ARG_Fast_Globox", { "ARG_Ginit", "ARG_GqueFaire", "ARG_Gjoue", "ARG_GvaAuWP", "ARG_GpoursuitRM", "ARG_Gdanse", "ARG_GsautDebut", "ARG_GsautMilieu", "ARG_GsautFin", "ARG_GtourneVersWP", "ARG_Gfuit", "ARG_Gpeur", "ARG_GfuitAuWp", "ARG_GpretAsauter", "ARG_Ginit_Entree2", "ARG_GattendRaymond", "JAC_GAttendUnPeu" }},
    {"SUN_Grille_Cage", { "SUN_Grille_Init", "SUN_Grille_Normal", "ARG_Grille_Montee", "ARG_Grille_Monte", "ARG_Grille_Descend" }},
    {"JEZ_PorteLaser", { "JEZ_Porte_Laser_init", "CHR_PL_Ouvert", "CHR_PL_Ferme", "CHR_PL_Fermeture", "CHR_PL_Ouverture", "CHR_PL_Nothing", "GRP_SansComp" }},
    {"GRP_Fin_Glob_10", { "GRP_CestLaFin", "DS1_Teleportation", "DS1_Cinematique" }},
    {"Levelglob_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"MIC_CheckPointAccessoire", { "MIC_CheckAcc_INIT", "MIC_CheckAcc_Deplace" }},
    {"SDZ_Glob_Cine", { "SDZ_Glob10_0_Init", "SDZ_Glob10_1_THX" }},
    {"OLP_PlateForme_Fleur", { "OLP_Fleur_Init", "OLP_Fleur_Desactivee", "OLP_Fleur_Monte", "OLP_Fleur_Tombe", "OLP_Fleur_Debut", "OLP_Fleur_Avance", "OLP_Fleur_Stop", "OLP_Fleur_Recule" }},
    {"CHR_BuissonCacheur", { "OLP_Buisson_Init", "ARG_DistanceRM", "PHL_Buisson_Wait", "ARG_Appear", "ARG_ControleMario", "ARG_Cpt_Vide", "ARG_Pousse", "DS1_DistanceRayBis", "ARG_Saute", "DS1_SpecialRevisite" }},
    {"GRP_Assaut_Nef", { "GRP_Passage", "GRP_FinAssaut", "GRP_attend_Destruction", "GRP_Vide", "GRP_Initialisation", "GRP_AttendDetection", "DS1_Gratification" }},
    {"LevelGlob_20", { "YLT_InitLevel", "YLT_LevelLoop", "BNT_Revisite" }},
    {"SUN_Globox_Cinema", { "SUN_Glo_Cine_Init", "SUN_Glo_Cine_THX", "SUN_Glo_Cine_AideJoueur" }},
    {"NIK_Ray_Glob20", { "NIK_Ray_Glob20_Init", "NIK_Ray_Glob20_THX" }},
    {"ARG_SpotAuSol", { "ARG_Spotinit", "ARG_SpotMain", "ARG_SpotSuitRM" }},
    {"LevelGlob_30", { "YLT_InitLevel", "YLT_LevelLoop", "ARG_AttendContact", "ARG_SynchroMusique" }},
    {"ARG_Araignee", { "ARG_Init", "ARG_Rezo_OuEstRayman", "ARG_Rezo_Marche", "ARG_Attaque", "ARG_SautSpider", "ARG_SautFinSpider", "ARG_Rezo_Marche_DansWp", "ARG_SpiderVide", "ARG_SautReceptionSubroutine" }},
    {"ARG_Transparence_Light", { "ARG_TL_init", "ARG_TL_detect", "ARG_TL_actif" }},
    {"Levelhelic_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"SUN_GenWind_Mod", { "SUN_GenWind_Init", "SUN_GenWind_Normal", "SUN_GenWind_Sphere", "SUN_GenWind_Tourbillon", "SUN_GenWind_Boite", "SUN_GenWind_Vertical", "SUN_GenWind_Bloquant", "SUN_GenWind_Rien" }},
    {"SUN_Pyramide_Feu", { "SUN_Pyramid_Init", "SUN_Pyramid_Normal", "SUN_Pyramid_Crache", "SUN_Pyramid_Tourne1", "SUN_Pyramid_Tourne2", "SUN_Pyramid_Tourne3" }},
    {"STN_Portaykl_ginreita", { "STN_ginreita_init", "STN_ginreita_genere", "STN_genreita_doc" }},
    {"STN_viseur", { "STN_viseur_init", "STN_viseur_oriente" }},
    {"STN_dogcam", { "STN_dogcam_init", "STN_dogcam_boucle", "STN_dogcam_detect" }},
    {"SDZ_Ray_Helic10", { "SDZ_Dum_0_Init", "SDZ_Dum_1_THX" }},
    {"SDZ_Porte_Helic20_Cine", { "SDZ_Matos_0_Init", "SDZ_Matos_1_THX" }},
    {"SDZ_RayZin", { "SDZ_Dum_1_THX", "SDZ_Dum_0_Init" }},
    {"NIK_garde_tfeu_cine", { "SDZ_Feu_0_Init", "SDZ_Feu_1_THX" }},
    {"Levelhelic_20", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"MIC_NoFreeLookBordel", { "MIC_NFLB_INIT" }},
    {"LevelHelic_30", { "YLT_InitLevel", "STN_Level_boucleAOJ", "STN_Level_check_Toiles", "STN_Level_check_Stalac", "STN_Level_check_Gardfeu", "STN_Level_debutAOJ", "STN_Level_finAOJ", "STN_Level_check_Raytime", "STN_Level_attend_cine" }},
    {"STN_fayagwod", { "STN_Fayagwod_init", "STN_Fayagwod_move", "STN_Fayagwod_wall", "STN_Fayagwod_shoot", "STN_Fayagwod_stalac", "STN_Fayagwod_tornado", "STN_Fayagwod_dead" }},
    {"STN_Railcam", { "STN_Railcam_init", "STN_Railcam_detect", "STN_Railcam_work" }},
    {"STN_pied_jack_on", { "STN_piejacon_init", "STN_piejacon_wait", "STN_piejacon_chute", "STN_piejacon_PAF", "STN_piejacon_vise", "STN_piejacon_the_end" }},
    {"NIK_Ray_Helic30", { "NIK_Ray_Helic30_Init", "NIK_Ray_Helic30_THX" }},
    {"SUN_Cam_Distance", { "SUN_CamDist_Init", "SUN_CamDist_Normal" }},
    {"Levelile_10", { "YLT_InitLevel" }},
    {"MIC_MenhirSauteur", { "MIC_MenSau_INIT", "MIC_MenSau_AttendSecousse", "MIC_MenSau_Saute", "MIC_MenSau_Attente", "MIC_MenSau_Vole" }},
    {"MIC_GenNInterrupteurs", { "MIC_GenNI_INIT", "MIC_GenNI_Surveille" }},
    {"MIC_GoretsEnPrison", { "MIC_GoPri_INIT", "MIC_GoPri_Attente", "MIC_GoPri_Evasion", "MIC_Gopri_Panique" }},
    {"MIC_CaisseFlottante", { "MIC_CaisseFlot_INIT", "MIC_CaisseFlot_Flotte", "MIC_Caisse_AttendSecousse", "MIC_Caisse_Saute", "MIC_Caisse_Attente", "MIC_Caisse_SauteAuPif" }},
    {"MIC_SuperPoussin", { "MIC_SuPo_INIT", "MIC_Supo_Promenade_Tourne", "MIC_SuPo_Promenade_Pause", "MIC_SuPo_Promenade_Avance", "MIC_SuPo_Promenade_Saute", "MIC_SuPo_Poursuite_Avance", "MIC_SuPo_Promenade_EarthQuake", "MIC_SuPo_Poursuite_Debut", "MIC_SuPo_Poursuite_Pause", "MIC_SuPo_Poursuite_RetourAuCentre" }},
    {"IVN_nef_cine_intro", { "IVN_nef_forward_forward", "IVN_nef_forward_stop", "IVN_nef_void", "IVN_nef_roll_left", "IVN_nef_roll_right", "IVN_nef_roll_stop", "IVN_nef_roll_stab", "IVN_nef_init", "IVN_nef_roll_stab_smooth", "IVN_nef_inc_coeff", "IVN_nef_dec_coeff", "IVN_nef_pitch_backward", "IVN_nef_pitch_forward", "IVN_nef_pitch_stab", "IVN_nef_pitch_stab_smooth", "IVN_nef_pitch_stop", "MOM_suitReseau_init", "MOM_suitReseau_idle" }},
    {"LevelJail_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"IVN_incline_cam_dans_cine", { "IVN_00_init", "IVN_01_roll_left", "IVN_02_roll_right", "IVN_03_reset", "IVN_04_stop", "IVN_05_reset_smooth", "IVN_06_void" }},
    {"MOM_eboulisMod", { "MOM_eboulis_init", "MOM_eboulis_normal" }},
    {"MOM_ray2tgeMod", { "MOM_logo_init", "MOM_logo_affiche", "MOM_Logo_Fadein", "MOM_Logo_FadeOut" }},
    {"SUN_Ray_Logos", { "SUN_Logos_Init", "SUN_Logos_Fadein", "SUN_Logos_FadeOut", "SUN_Logos_Affiche" }},
    {"OLD_Helice01", { "SUN_Init", "SUN_Tourne" }},
    {"Leveljail_20", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"SUN_Barriere_Laser_Cine", { "SUN_BarrLaser_Cine_Init", "SUN_BarrLaser_Cine_THX" }},
    {"SUN_RayDummy_Intro", { "SUN_DumIntro_Init", "SUN_DumIntro_THX" }},
    {"SUN_Grille_Cine", { "SUN_Grille_Init", "SUN_Grille_Loop", "SUN_Grille_Paf" }},
    {"SUN_Sbire_Glob_Cine", { "SUN_SbireG_Init", "SUN_SbireG_THX" }},
    {"SUN_Papillon", { "SUN_Popoi_Init", "SUN_Popoi_Cherche", "SUN_Popoi_balade" }},
    {"SUN_3B_Globox_Cine", { "SUN_3B_Gbx_Init", "SUN_3B_Gbx_THX" }},
    {"SDZ_Ray_Learn60", { "SDZ_Dum_0_Init", "SDZ_Dum_1_THX" }},
    {"MIC_LeverDuJour", { "MIC_LDJ_INIT", "MIC_LDJ_IlVaBientotArriver" }},
    {"SDZ_FinLearn10", { "SDZ_Nego_0_Init", "SDZ_Nego_1_Normal", "SDZ_Nego_2_Attente_Distance", "SDZ_Nego_3_Attente_Cage", "SDZ_Nego_4_Fin" }},
    {"YAM_GenPoloc", { "YAM_GenPoloc0Init", "YAM_GenPoloc1Go", "JCP_GenPoloc1Murfy", "JCP_GenPoloc1AttendCage", "JCP_GenPoloc2Fin", "JCP_GenPoloc1Rayseau" }},
    {"ARG_Transparence", { "ARG_Trans_Init", "ARG_Trans_Detection", "ARG_Trans_Actif", "ARG_Trans_Actif_RM" }},
    {"STH_TargetCam", { "STH_target_init" }},
    {"LevelLearn_10", { "YLT_InitLevel", "YLT_LevelLoop", "JCP_LevelLoop2", "JCP_LevelLoop3", "YGE_Fade" }},
    {"SDZ_Pitizetre_Cine", { "SDZ_Pitz_0_Init", "SDZ_Pitz_1_THX" }},
    {"SUN_Poisson_Rigol_M", { "SUN_Poi_Rigol_Init", "SUN_Poi_Rigol_Lum", "SUN_Poi_Rigol_Normal", "SUN_Poi_Rigol_Normal2", "SUN_Poi_Rigol_Normal3", "SUN_Poi_Rigol_retour" }},
    {"DS1_pti", { "FRH_sou_init", "FRH_sou_marche" }},
    {"DS1_OneShotCondition", { "DS1_Init_Sound_Oiseau2", "DS1_Start_Oiseau2", "DS1_Init_Sound_Mouette", "DS1_Start_Sound_Mouette", "DS1_Init_Sound_Sonar", "DS1_Start_Sound_Sonar", "DS1_Init_Sound_Vagues", "DS1_Start_Sound_Vagues", "DS1_Init_Sound_UnderB", "DS1_Start_Sound_UnderB", "DS1_Test_ActivRaymanSonar", "DS1_Test_ActivRaymanUnderB" }},
    {"DS1_SwitchBouclant", { "DS1_InitSonCascade", "DS1_TestSurfaceSonCascade", "DS1_TestFinSonCascade", "DS1_InitSonUnderW", "DS1_Test_ActivRaymanUnderW", "DS1_Test_SurfaceSonUnderW", "DS1_InitSonSwitchVent", "DS1_TestSurfaceSonVent", "DS1_Test_FinSonUnderW", "DS1_InitSonSwitchForet", "DS1_TestSurfaceSonForet", "DS1_TestFinSonSwitchForet", "DS1_TestFinSonSwitchVent" }},
    {"PHL_Actor_Model2", { "PHL_Champ_Komport", "PHL_Champ_Init" }},
    {"LevelLearn_30", { "YLT_InitLevel" }},
    {"LevelLearn_31", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"ELR_mPrisme", { "ELR_C_Prisme_00_Init", "ELR_C_Prisme_01Detection", "ELR_C_Prisme_02Ramasse" }},
    {"BNT_BancDePetitsPiranhasTeigneux", { "MIC_BancPir_Init", "MIC_BancPir_MiaMiam" }},
    {"SUN_Barriere_Elec", { "SUN_Barriere_Elec_Init", "SUN_Barriere_Elec_Normal", "SUN_Barriere_Elec_INTER" }},
    {"LevelLearn_40", { "YLT_InitLevel", "YLT_LevelLoop", "STN_FinMap", "STN_Youpi" }},
    {"DS1_GestionPaireInterrupteur", { "DS1_GestionInterrupteur_Init", "DS1_CheckLumieres", "DS1_CheckLumieres_with_lums" }},
    {"IVN_Sbire_Bombe", { "IVN_gn_init", "IVN_gn_deplace_init", "IVN_gn_deplace_capa", "IVN_gn_deplace_impossible", "IVN_gn_deplace_next", "IVN_gn_choix_action", "IVN_gn_crochet", "IVN_gn_saute", "IVN_gn_shoot", "IVN_gn_insert", "IVN_gn_mort", "IVN_gn_to_lance", "IVN_gn_to_tourne", "IVN_gn_to_surveil", "IVN_gn_courir", "IVN_gn_avant_detection", "IVN_gn_chute_inf" }},
    {"STN_stilwil", { "STN_stilwil_init", "STN_stilwil_turn", "STN_stilwil_turn_relatif" }},
    {"LevelLearn_60", { "YLT_InitLevel" }},
    {"OLP_Vent_Vertical", { "OLP_Init_Vent", "OLP_En_Fonction" }},
    {"MIC_GenSalleMagique", { "MIC_SalleM_INIT", "MIC_SalleM_WizPof" }},
    {"LevelLiber_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"SUN_ToutLeMondeIlEstLibre", { "SUN_OnEstLibres_Init", "SUN_OnEstLibres_THX" }},
    {"SUN_FautFilmerToutCa", { "SUN_VasyMetsLaK7_Init", "SUN_VasyMetsLaK7_THX" }},
    {"SUN_check_point", { "OLD_chkp_init", "OLD_chkp_vide" }},
    {"LevelLy_10", { "YLT_InitLevel", "YLT_LevelLoop", "GRP_world_vide" }},
    {"OLD_fee_ly", { "OLD_ly_init", "ARG_Init_Special_JCP", "MTR_ly_Init", "MTR_ly_Attente_Depart", "MTR_ly_Ballade", "MTR_ly_Saut", "MTR_ly_Recherche", "MTR_ly_Tourne", "MTR_ly_Attente_RM", "MTR_ly_Init_Chemin", "MTR_ly_Nage", "MTR_Ly_Sort_Eau", "MTR_ly_Attente", "MTR_ly_Attente_sur_PF" }},
    {"GRP_HorsLimite", { "GRP_MoyenDeDetection", "GRP_DetectionZone", "GRP_DetectionHauteur", "GRP_OnRepart", "DS1_DeuxiemePartie", "DS1_AttenteMegaShoot" }},
    {"GRP_TimerCourse", { "GRP_Init", "GRP_GestionTemps", "GRP_ByeBye", "GRP_AttendFinMadeIt", "DS1_RetourMapMonde", "DS1_GestionAffichage", "DS1_RetourAffichage", "DS1_Vide" }},
    {"GRP_CestFini", { "GRP_Init", "GRP_FinCourse" }},
    {"DS1_Affichage", { "DS1_Initialisation", "DS1_Affiche", "DS1_PrepareTexte", "DS1_Bye", "DS1_Disparition", "DS1_AttendBouton", "DS1_PourMapsCourse", "DS1_GestionPage" }},
    {"GRP_Toile_Trampoline", { "GRP_Touche_Toile" }},
    {"CHR_Apparition", {  }},
    {"LevelLy_20", { "YLT_InitLevel", "YLT_LevelLoop", "GRP_World_Vide" }},
    {"GRP_Generateur_Nenuphar", { "GRP_Initialisation", "DS1_GenerationInfinie" }},
    {"OLD_nenuphar", { "OLD_nenu_init", "OLD_nenu_reseau" }},
    {"YAM_RayMonde", { "YAM_C_RayMonde0Init", "YAM_C_RayMonde2VaAuWpt", "YAM_C_RayMonde3Retournement", "YAM_C_RayMonde1Arret", "YAM_C_RayMonde0Chute" }},
    {"LevelMapmonde2", { "YLT_InitLevel" }},
    {"YAM_GenInitMapmonde", { "YAM_C_GenInitMapmonde0Init", "YAM_C_GenInitMapmonde1TraiteLevel", "YAM_C_GenInitMapmonde2DessineChemin", "YAM_C_GenInitMapmonde3Standard", "YAM_C_GenInitMapmonde4Zoom", "YAM_C_GenInitMapmonde5Fin", "NIK_JEFF_OnAttendLeMenu" }},
    {"YAM_PastilleMapmonde2", { "YAM_C_PastilleMapmonde0Init", "YAM_C_PastilleMapmonde1Visible", "YAM_C_PastilleMapmonde2Invisible" }},
    {"NIK_GenAutoSave", { "NIK_C_Init", "NIK_C_Loop_SaveOK", "NIK_C_Loop_NogameSave", "NIK_C_Loop_VMSIOError", "NIK_C_Write_Message" }},
    {"NIK_Gen_EcranStart", { "NIK_C_Init", "NIK_C_AfficheMenuStart", "NIK_C_GotoMenu3D" }},
    {"Levelmenu", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"YAM_Baleine", { "YAM_Baleine1Avance", "YAM_Baleine0Init" }},
    {"YAM_PtizetreMenu", { "YAM_PtitZetreMenu1Normal", "YAM_PtitZetreMenu0Init" }},
    {"MIC_Krab", { "MIC_Krab_INIT", "MIC_Krab_Bouge", "MIC_Krab_Tourne" }},
    {"YAM_GenMenuSimple", { "YAM_C_GenMenuSimple_Apparition", "YAM_C_GenMenuSimple_Disparition", "YAM_C_GenMenuSimple_MenuPrincipal", "YAM_C_GenMenuSimple_Init", "NIK_C_GenMenusimple_MenuOptions", "NIK_C_GenMenuSimple_MenuSon", "NIK_C_GenMenuSimple_MenuLangue", "NIK_C_GenMenuSimple_MenuVideo", "NIK_C_GenMenuSimple_MenuCharger", "NIK_C_GenMenuSimple_MenuNew", "NIK_C_GenMenuSimple_Try60Hz", "NIK_C_GenMenuSimple_Valide60Hz", "NIK_C_GenMenuSimple_Indique4_3_ou_16_9", "NIK_C_GenMenuSimple_ChangeMap", "NIK_C_SelectVMS", "NIK_C_Void", "NIK_C_Centrage_Ecran", "NIK_C_WarningRewriteNewGame", "NIK_C_ConfirmCreateGame", "NIK_C_Confirm_LoadGame", "NIK_C_Load_Options", "NIK_C_Load_Mode16_9", "NIK_C_Load_Mode_60h", "NIK_C_Load_RumblePack", "NIK_C_GenMenuSimple_MenuEraseASlot", "NIK_C_Interruption_Option", "NIK_C_OtpionLoad_Try60hz", "NIK_C_OtpionLoad_Valid60Hz", "NIK_C_OptionLoad_Indique4_3_ou_16_9", "NIK_C_VMSFULL_RM_Warningerase", "NIK_JFF_WAIT_RUMBLE1", "NIK_JFF_RumbleError", "NIK_JFF_WAIT_RUMBLE2", "NIK_JFF_RumbleError2", "NIK_JFF_OptionCorrupt", "NIK_JFF_VMS_Corrupt", "NIK_JFF_VMS_CorruptLoad", "NIK_JFF_OptionOk" }},
    {"YAM_GenCibleCamera", { "YAM_GenCibleCamera0Init", "YAM_GenCibleCamera1Normal" }},
    {"ARG_Martin_Pecheur", { "ARG_MP01_init", "ARG_MP02_vol", "ARG_MP03_VersWp", "ARG_MP04_EviteMur", "ARG_MP05_Redresse", "ARG_MP06_Plonge", "ARG_MP07_Remonte" }},
    {"NIK_Popolipoi_Menu_DC", { "NIK_C_Init", "NIK_C_Vol", "NIK_C_Wait" }},
    {"Levelmine_10", { "YLT_InitLevel" }},
    {"MIC_Nef_ARaymond", { "MIC_NefARem_INIT", "MIC_NefARem_Vol", "MIC_NefARem_Accoste", "MIC_NefARem_AQuai", "MIC_NefARem_Destruction", "MIC_NefARem_Paf", "MIC_NefARem_DemiTOur", "MIC_NefARem_Fin" }},
    {"MIC_QuaiPourNef", { "MIC_QPN_INIT", "MIC_QPN_Surveille", "MIC_QPN_Approche", "MIC_QPN_AttendBbGlob", "MIC_QPN_GenereGorets", "MIC_QPN_Delai", "MIC_QPN_EnVeille" }},
    {"OLD_bastion_cassable", { "MIC_Bast_INIT", "MIC_Bast_Surveille", "MIC_Bast_Chute", "MIC_Bast_Disparait" }},
    {"MIC_TesteNefPleine", { "MIC_TNP_INIT", "MIC_TNP_Surveille" }},
    {"MOM_Ray_Mines10_model", { "MOM_Ray_Mines10_init", "MOM_Ray_Mines10_THX" }},
    {"MOM_mines10F", { "MOM_Gen_detectPerso_init", "MOM_Gen_detectPerso_thx" }},
    {"MOM_Globette_Cine_Mod", { "MOM_Globette_M10_init", "MOM_Globette_M10_thx" }},
    {"MOM_Collision", { "MOM_collision_init", "MOM_collision_THX", "MOM_AttenteFInTHX" }},
    {"MIC_GoretsMineurs", { "MIC_GoMin_INIT", "MIC_GoMin_VersLaNef" }},
    {"Levelmorb_00", { "YLT_InitLevel", "YLT_LevelLoop", "ARG_Cinema", "ARG_PrepareCine", "ARG_LoopDansTour", "ARG_Fin", "ARG_FinLoop" }},
    {"ARG_Vase_Flotte", { "ARG_TVinit", "ARG_TVwait", "ARG_TVmonte", "ARG_TVrien", "DS1_mONTE2" }},
    {"ARG_BrasJano", { "ARG_BJ_Init", "ARG_BJ_Sort", "ARG_BJ_Attrappe", "ARG_BJ_Rentre", "ARG_BJ_Paf", "ARG_BJ_FauxRM" }},
    {"OLD_SBIRE_lance", { "OLD_SBIRE_lance_init", "OLD_SBIRE_lance_mort", "OLD_SBIRE_lance_lance", "OLD_SBIRE_lance_tourne", "MIC_SBIRE_lance_Surveille", "MIC_SBIRE_lance_Delai" }},
    {"SUN_engrenage", { "SUN_eng_init", "SUN_eng_test" }},
    {"SUN_grillio", { "CHR_gri_init", "CHR_gri_bouge", "MIC_gri_Surveille", "MIC_gri_Chute", "STN_gri_attente", "STN_gri_descend" }},
    {"Levelmorb_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"DS1_Change_Map", { "DS1_Change_Map_Init", "DS1_Change_Map_Teleport" }},
    {"XAP_World_SM1", { "XAP_Init_Level" }},
    {"XAP_World_SM2", { "XAP_Init_Level", "XAP_Level_loop", "XAP_FadePoulet", "XAP_FadePoulet2" }},
    {"XAP_World_SM3", { "XAP_Init_Level" }},
    {"MIC_SauveCB28", { "MIC_SCB28_INIT", "MIC_SCB28_Surveille" }},
    {"XAP_Figntable", { "XAP_Init" }},
    {"OLD_tonneau_vase", { "OLD_ton_vase_pilier_init", "OLD_ton_vase_pilier_monte3", "OLD_ton_vase_pilier_normal", "OLD_ton_vase_pilier_tombe", "OLD_ton_vase_pilier_tombe2", "OLD_ton_vase_pilier_tombe3", "OLD_ton_vase_pilier_tombe4" }},
    {"LevelMorb_20", { "YLT_InitLevel", "STN_Level_finAOJ", "STN_Level_boucleAOJ", "STN_Level_debutAOJ", "STN_Level_check_Clark", "STN_Level_Check_Switch", "STN_Level_check_Chute", "STN_Level_check_Boite", "ARG_NeFaitRien" }},
    {"SUN_Clarky", { "SUN_Clark_Init", "SUN_Clark_SuitRay", "SUN_Clark_Attente1", "SUN_Clark_saut", "SUN_Clark_Boum", "SUN_Clark_ChopeRay", "SUN_Clark_Course", "STN_Clark_JetteRay", "STN_Clark_AuSol" }},
    {"SUN_Cine_Ray_Clark", { "SUN_CineClark_Init", "SUN_CineClark_Detec", "SUN_CineClark_Apex", "SUN_CineClark_Plan01", "SUN_CineClark_Plan02", "SUN_CineClark_Plan03", "SUN_CineClark_Plan04", "SUN_CineClark_Plan05", "SUN_CineClark_Plan06", "SUN_CineClark_Plan07", "SUN_CineClark_Plan08", "SUN_CineClark_Plan09", "SUN_CineClark_Plan10", "SUN_CineClark_Plan11", "SUN_CineClark_Plan12", "SUN_CineClark_Plan13", "SUN_CineClark_Plan09b", "SUN_Cineclark_Fin", "SUN_CineClark_Plan14", "SUN_CineClark_Chemin", "SUN_CineClark_Plan2_1", "SUN_CineClark_Plan2_2", "SUN_CineClark_Plan2_4", "XAP_CineClark_Rien", "SUN_CineClark_Plan2_5", "SUN_CineClark_Plan2_3", "SUN_CineClark_Plan2_6" }},
    {"XAP_Check_Inter", { "XAP_Check_Init", "XAP_Check_check", "XAP_fin_son" }},
    {"DS1_Offset_Perso", { "DS1_Offset_Init" }},
    {"STH_cible", { "STH_cible_init", "STH_cible_main", "STH_cible_main2", "STH_cible_main3" }},
    {"SUN_RayDum_Clark", { "SUN_Ray_Morb20_Init", "SUN_Ray_Morb20_THX" }},
    {"LevelNave_10", { "YLT_InitLevel" }},
    {"STN_filetGI", { "STN_filet_init", "STN_filet_detecte", "STN_filet_detruit", "STN_filet_tremble" }},
    {"STN_pitibastion", { "STN_pitibastion_init", "STN_pitibastion_detecte", "STN_pitibastion_tremble", "STN_pitibastion_chute", "STN_pitibastion_detruit", "STN_pitibastion_ecroule", "YLT_PetiteChute" }},
    {"STN_pont", { "STN_pont_init", "STN_pont_detection", "STN_pont_nocpt", "STN_pont_tourne", "STN_pont_detruit", "STN_pont_ecroule", "STN_pont_tremble", "STN_pont_tremble_init", "STN_pont_detecte_rayman" }},
    {"LevelNave_15", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"DS1_WaterQuiMonte", { "DS1_Flood_Init", "DS1_Flood_Main", "DS1_Flood_Stop", "DS1_Flood_detect" }},
    {"STH_grue_tour", { "STH_grue_tour_init", "STH_grue_tour_fin" }},
    {"MIC_GenTuePirateALeau", { "MIC_TPAL_INIT", "MIC_TPAL_AttendPersoValide", "MIC_TPAL_TesteLePerso" }},
    {"STH_28", { "STH_28_init", "STH_28_Main" }},
    {"STH_generateur_boulets", { "STH_generateur_init", "STH_generateur_bombardeRM", "DS1_TirReprend" }},
    {"LevelNave_20", { "YLT_InitLevel" }},
    {"STH_vie_eternelle", { "STH_vie_init", "STH_vie_main" }},
    {"Levelnego_10", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"NIK_Ray_Nego", { "NIK_Ray_Nego_Init", "NIK_Ray_Nego_THX" }},
    {"NIK_Porte_Ptizetre", { "NIK_Porte_Ptizetre_Init", "NIK_Porte_Ptizetre_THX" }},
    {"NIK_Ptizetre_nego_cine", { "NIK_Ptizetre_Nego_Cine_Init", "NIK_Ptizetre_Nego_Cine_THX" }},
    {"LevelPlum_00", { "YLT_InitLevel", "DS1_Level_loop" }},
    {"MIC_MonstroPlante", { "MIC_MP_INIT", "MIC_MP_Cache", "MIC_MP_SeMontre", "MIC_MP_Deplacement", "MIC_MP_Approche", "MIC_MP_Fuite", "MIC_MP_SeCache", "MIC_MP_Argh_Damned", "MIC_MP_Montee", "MIC_MP_Descente", "MIC_MP_Youpi", "MIC_MP_YoupiFin" }},
    {"CHR_inter", { "CHR_inter_init", "CHR_inter_go" }},
    {"MIC_RadarTournant", { "MIC_Radar_INIT" }},
    {"YAL_plum00_2eSM", { "YAL_simulworld" }},
    {"YAL_plum00_1ereSM", { "YAL_simulworld" }},
    {"MIC_DalleCassee", { "MIC_Dalle_INIT", "MIC_Dalle_Surveille", "MIC_Dalle_Chute" }},
    {"YAL_Plum10_3eSM", { "YAL_simulworld" }},
    {"SUN_magie_simple", { "SUN_magie_init", "SUN_magie_CB", "SUN_Magie_go" }},
    {"ZOR_PyramideCrachante", { "ZOR_INITPyrCrach", "ZOR_PyrAttenteGendoor", "ZOR_RIENPyr", "ZOR_PyrChoixProjectile", "ARG_Rotation", "ARG_FlammeON", "ARG_FlammeOFF", "DS1_RetourFlammes" }},
    {"SUN_magic_key", { "SUN_MC_init", "SUN_MC_attente_activation", "SUN_MC_go_air", "SUN_MC_porte", "SUN_MC_go_sol" }},
    {"LevelPlum_10", { "YLT_InitLevel", "XAP_Level_Loop" }},
    {"STN_Aimant", { "STN_Aimant_init", "STN_Aimant_detect_in", "STN_Aimant_attire", "STN_Aimant_detect_out", "STN_Aimant_magic_check", "STN_Aimant_magic_control", "YAL_aimantbis_attire", "STN_Aimant_magic_direct" }},
    {"STN_tour_nique", { "STN_tourniquet_init", "STN_tourniquet_detect_up", "STN_tourniquet_turn_up", "STN_tourniquet_detect_closed" }},
    {"MIC_GeantVert", { "MIC_Colosse_INIT", "MIC_Colosse_Avance", "MIC_Colosse_AttendFils", "MIC_Colosse_AttendInterrupteur", "MIC_Colosse_MarcheDebut", "MIC_Colosse_Tremble" }},
    {"YAL_Plum10_2eSM", { "YAL_Simulworld", "DS1_SimulLoop" }},
    {"ALG_Plum10_4eSM", { "ALG_Simulworld" }},
    {"ALG_Plum10_1ereSM", { "ALG_Simulworld" }},
    {"MIC_TeleportKiCroyaitPrendre", { "MIC_TPKCP_INIT", "MIC_TPKCP_Surveille" }},
    {"MIC_Desactivateur", { "MIC_Zig_INIT", "MIC_Zig_Attente" }},
    {"XAP_Apparition", { "XAP_Init" }},
    {"XAP_Plum_teleport", { "XAP_Init" }},
    {"DS1_Plum_Teleport2", { "DS1_Init" }},
    {"DS1_Plum_Teleport3", { "DS1_Init" }},
    {"MIC_TeteDuGeantVert", { "MIC_TGV_INIT", "MIC_TGV_Dessus", "MIC_TGV_AttendCam" }},
    {"ZOR_CracheLave", { "ZOR_INITCracheLave", "ZOR_RIENCracheLave", "ZOR_FINCracheLave", "VCT_JeFaisMal" }},
    {"Levelplum_20", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"BNT_StalagBase_Model", { "MIC_StalakBase_INIT", "MIC_StalakBase_Attend" }},
    {"MIC_FireWorm", { "MIC_FireW_INIT", "MIC_FireW_Surveille", "MIC_FireW_Attak_Rampe", "MIC_FireW_Attak_Saute" }},
    {"MIC_Rafteuse", { "MIC_Raft_INIT", "MIC_Raft_Avance", "MIC_Raft_AttendRM" }},
    {"MIC_Colonne", { "MIC_Colon_INIT", "MIC_Colon_Tombe", "MIC_Colon_Surveille", "MIC_Colon_VireSparadrap" }},
    {"BNT_StalagPF_Model", { "MIC_PFStal_INIT", "MIC_PFStal_Attente", "MIC_PFStal_Tombe", "MIC_PFStal_FlotteSurPlace", "MIC_PFStal_Flotte", "MIC_PFStal_Coule", "JCP_PFStal_FlotteSurPlaceAvecChrono" }},
    {"LevelPoloc_10", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"NIK_Cine_Poloc", { "NIK_Cine_Poloc_Init", "NIK_Cine_Poloc_THX" }},
    {"LevelPoloc_20", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"LevelPoloc_30", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"NIK_cine_poloc2", { "NIK_Cine_Poloc2_Init", "NIK_Cine_Poloc2_THX" }},
    {"LevelPoloc_40", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"NIK_Gen_Raycap", { "NIK_0_Init", "NIK_1_InitAffiche", "NIK_2_Affiche", "NIK_3_FinAffiche" }},
    {"LevelRaycap", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"DS1_gen_sound", { "DS1_init" }},
    {"LevelRhop_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"OLD_shoot_zde", { "OLD_shoot_zde_init", "OLD_shoot_zde_base" }},
    {"OLD_shoot_laser_rouge", { "OLD_shoot_cible_init", "OLD_shoot_cible_normal" }},
    {"OLD_boule_energie", { "OLD_b_energ_init", "OLD_b_energ_wait", "OLD_b_energ_suit", "FRH_b_energ_rnd" }},
    {"FRH_ouestu", { "FRH_ou_init", "FRH_ou_cbit" }},
    {"DS1_teleport", { "DS1_teleport_init", "old_teleport_fade_out", "old_teleport_fade_in", "DS1_zob" }},
    {"FRH_Plaque_lave", { "FRH_plk_init", "FRH_plk_go", "FRH_plk_monte", "FRH_plk_descent", "DS1_plk_wait" }},
    {"SUN_Grille_Rhop_Cine", { "SUN_gril_init", "SUN_gril_THX", "SUN_gril_Combat", "DS1_gril_chute", "DS1_gril_init2" }},
    {"SUN_Boulet_Cine", { "SUN_Bou_Cine_Init", "SUN_Bou_Cine_THX" }},
    {"SUN_RayRhop", { "SUN_RayRhop_Init", "SUN_RayRhop_THX" }},
    {"SUN_Rhop_Cinema", { "SUN_Rh_Cine_Init", "SUN_Rh_Cine_THX" }},
    {"SUN_Tuyo_ASC_Cine", { "SUN_Tuyo_Cine_Init", "SUN_Tuyo_Cine_THX" }},
    {"SUN_Obus_Rhop", { "SUN_Obus_Init", "SUN_Obus_THX" }},
    {"SUN_LY_Rhop", { "SUN_LY_Rhop_Init", "SUN_LY_Rhop_THX" }},
    {"SUN_Lums_Rhop", { "SUN_Lums_Init", "SUN_Lums_THX" }},
    {"SUN_Batam_Rhop", { "SUN_Batam_Init", "SUN_Batam_THX" }},
    {"SUN_Flash_Cine", { "SUN_Flash_Init", "SUN_Flash_THX" }},
    {"SUN_Nuage_cine", { "SUN_Nuage_Init", "SUN_Nuage_THX" }},
    {"SUN_Debris_Cine", { "SUN_Debris_Init", "SUN_Debris_THX" }},
    {"SUN_Reactivator2000", {  }},
    {"SUN_Interieur_Rhop_Cine", { "SUN_IntRhop_Cine_Init", "SUN_IntRhop_Cine_THX" }},
    {"SUN_Rhop_MK1", { "OLD_Rhop_Init", "OLD_Rhop_Bombes", "OLD_Rhop_Marchatak", "OLD_Rhop_SautDeb", "OLD_Rhop_Saut", "DS1_2rhop_init_phase2_sanscine", "OLD_2rhop_vrille_accroche", "OLD_2rhop_accroche", "OLD_2rhop_paf_accro", "OLD_2rhop_vol", "OLD_rhop_vide", "OLD_2rhop_mort", "OLD_rhop_marche", "OLD_rhop_trebuche", "OLD_2rhop_paf_accr_sol", "OLD_rhop_tourne_wp_central", "OLD_rhop_va_au_wp", "OLD_rhop_esquive", "OLD_rhop_lancer_bombes", "OLD_Rhop_init2", "FRH_2rhop_tir1", "FRH_2rhop_tir2", "FRH_2rhop_sautsimple", "DS1_2rhop_init_phase2_aveccine", "DS1_rhop_trebuche2" }},
    {"FRH_AreYouTalkingtome", { "FRH_talk_init", "FRH_talk_go" }},
    {"LevelRodeo_10", { "YLT_InitLevel", "YLT_LevelLoop", "OLP_Attente" }},
    {"OLP_Detruit_Missile", { "OLP_Init_Detruit_Missile", "OLP_Attente_Du_Missile" }},
    {"OLP_Grille", { "OLP_Grille_Init", "OLP_Ouverture_Grille", "OLP_Attend_Switch", "OLP_Grille_Fin" }},
    {"MOM_murfyCine", { "MOM_murfy_init", "MOM_THX_behaviour" }},
    {"DS1_BouclantCinematique", { "DS1_InitBruitMissileCine", "DS1_StartBruitMissileCine", "DS1_TestFinMissileCine", "DS1_InitAmbianceCinematiqueCascade", "DS1_StartAmbianceCascade", "DS1_TestFinFausseCascade" }},
    {"MOM_RayDum_encoreR10", { "MOM_RayDum_rodeo10_init", "MOM_RayDum_rodeo10_THX" }},
    {"OLP_DetruitPerso_A_Sa_Hauteur", { "OLP_Init_Destructeur_Perso", "OLP_Attend_Perso_Valide", "OLP_Test_Perso" }},
    {"LevelRodeo_40", { "YLT_InitLevel" }},
    {"JEZ_SlashRonce", { "JEZ_PtiteRonce_INIT", "JEZ_PtiteRonce_SLASH", "MIC_PtiteRonce_Tempo" }},
    {"STN_Clarck_Eolog", { "STN_Clarck_init", "STN_Clarck_way", "STN_Clarck_run", "STN_Clarck_walk", "STN_Clarck_wait", "STN_Clarck_follow" }},
    {"STN_murMUR", { "STN_murMUR_init", "STN_murMUR_check" }},
    {"SDZ_ClarkDum", { "SDZ_ClarkDum_0_Init", "SDZ_ClarkDum_1_THX" }},
    {"SDZ_FX_Rodeo40", { "SDZ_FX_0_Init", "SDZ_FX_1_Normal", "SDZ_FX_2_CheatCode", "SDZ_FX_3_Anim" }},
    {"LevelRodeo_60", { "YLT_InitLevel" }},
    {"SUN_Jokari", { "SUN_Menhir_Init", "MIC_Menhir_Surveille", "MIC_Menhir_Sortie" }},
    {"MIC_MenhirBourre", { "MIC_MenBour_INIT", "MIC_MenBour_JePenche", "MIC_MenBour_DoncJeChute", "MIC_MenBour_Boing" }},
    {"SUN_ObusR60_Cine", { "SUN_ObusR60_Init", "SUN_ObusR60_THX" }},
    {"SUN_GenSound_R60", { "SUN_SoundR60_Init", "SUN_SoundR60_Loop" }},
    {"SUN_Cam_R60_cine", { "SUN_CamAnimR60_Init", "SUN_CamAnimR60_THX" }},
    {"Levelseat_10", { "YLT_InitLevel", "YLT_LevelLoop", "YGE_Fade" }},
    {"BNT_SupportDuSiege", { "BNT_SupportDuSiegeInit", "BNT_SupportDuSiegeBoucle", "BNT_SupportDuSiegeAttendLaFin" }},
    {"VIM_Gen_Siege_Russe", { "VIM_gen_siege_init", "VIM_gen_siege_boucle" }},
    {"SDZ_PirateGorilleCine", { "SDZ_pgCine_Init", "SDZ_pgCine_SurSiege", "SDZ_pgCine_Chute", "SDZ_pgCine_SurTerre", "SDZ_pgCine_KillMe" }},
    {"SDZ_Ray_Seat10", { "SDZ_Dum_0_Init", "SDZ_Dum_1_Normal" }},
    {"VIM_Le_Gorille_tu_ecrases_hein", { "VIM_gor_init", "VIM_gor_vade_retro" }},
    {"YLT_SiegeRusse", { "BNT_ChaiseRusseInit", "BNT_ChaiseRusseBoucle", "BNT_AttendPourJeterRM", "BNT_ChaiseRusseAttendFinDeCinematique", "BNT_AttendLaMortDeRM" }},
    {"STN_Kapoum", { "STN_Kapoum_init", "STN_Kapoum_detecte", "STN_Kapoum_recule", "STN_Kapoum_Tir" }},
    {"STN_tonogear", { "STN_tonogear_init", "STN_tonogear_chemin", "STN_tonogear_alarme", "STN_tonogear_fire", "STN_tonogear_fireray", "STN_Tonogear_fixe", "STN_tonogear_boulet", "STN_tonogear_laser" }},
    {"LevelSeat_11", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"VIM_Cine_fin_seat_10", { "VIM_cine_init", "VIM_cine_cine", "VIM_cine_fin", "VIM_cine_detection", "SDZ_cine_aveccadre", "SDZ_cine_aveccadre2", "SDZ_cine_aveccadre3" }},
    {"ARG_Cam_Tunnel_XY", { "ARG_Cam_Init", "ARG_Cam_Attend_Rm", "ARG_Cam_XY" }},
    {"VIM_Detect_n_persos", { "VIM_n_perso_init", "VIM_n_perso_go" }},
    {"STN_boulet_moutarde", { "STN_boulet_moutarde_init", "STN_boulet_moutarde_go" }},
    {"LevelSki_10", { "YLT_InitLevel", "MIC_ActivePastille" }},
    {"MIC_PtiPiranhaSolo", { "MIC_PtiPiSolo_INIT" }},
    {"MIC_NewSerpentSki", { "MIC_NSP_INIT", "MIC_NSP_PrepareSki", "MIC_NSP_AttendRayman", "MIC_NSP_Ski", "MIC_NSP_Arret", "MIC_NSP_RuptureFaisceau" }},
    {"MIC_NewRaymanSki", { "MIC_NRS_Init", "MIC_NRS_SautDebut", "MIC_NRS_SautDescente", "MIC_NRS_SkiNormal", "MIC_NRS_Tremplin", "MIC_NRS_Paf", "MIC_NRS_PafFin", "MIC_NRS_Couche", "MIC_NRS_ElanFinal", "MIC_NRS_SousLeau", "MIC_NRS_Destruction", "MIC_NRS_Coule", "MIC_NRS_PrepareSortie", "MIC_NRS_Sortie" }},
    {"MIC_PouletFantome", { "MIC_PouFan_INIT", "MIC_PouFan_Cache", "MIC_PouFan_Vol" }},
    {"MOM_Serpent_Ski_THX", { "MOM_SerpSki_Init", "MOM_SerpSki_THX" }},
    {"MOM_JanoC_Vulca12", { "MOM_JanoC_Vulca12_init", "MOM_JanoC_Vulca12_THX" }},
    {"MIC_SuperCage", { "MIC_Blinder_INIT", "MIC_Blinder_Surveille" }},
    {"MIC_CamNoCol", { "MIC_CNC_INIT", "MIC_CNC_Surveille" }},
    {"MOM_Jano3", { "MOM_Jano3_init", "MOM_Jano3_biloSta" }},
    {"MOM_ski10", { "MOM_ski10_init", "MOM_ski10_biloSta" }},
    {"levelSki_60", { "YLT_InitLevel", "MIC_Ski60_TesteFin" }},
    {"MIC_BombeQuiTombe", { "MIC_BombeQT_INIT", "MIC_BombeQT_Tombe", "MIC_BombeQT_Attente" }},
    {"MOM_ray_ski60", { "MOM_ray_ski60_init", "MOM_ray_ski60_THX" }},
    {"MIC_Tremplin", { "MIC_Tremplin_INIT", "MIC_Tremplin_Coule", "JAC_Tremplin_monte", "JAC_Tremplin_descend" }},
    {"DS1_Staffman", { "DS1_staff_init", "DS1_staff_type1", "DS1_staff_type0" }},
    {"DS1_staff_pirate", { "DS1_stpir_init", "DS1_stpir_waitorcheat", "DS1_stpir_gowp", "DS1_ActiveCheat2" }},
    {"DS1_Goldorak", { "DS1_gol_init", "DS1_gol_go" }},
    {"DS1_lamort", { "DS1_kitu_init", "DS1_kitu_fade", "DS1_kitu_wait" }},
    {"Levelstaff_10", { "YLT_InitLevel", "YLT_LevelLoop", "DS1_wait", "DS1_end" }},
    {"DS1_go", { "DS1_go_init", "DS1_go_go", "DS1_go_fin" }},
    {"MIC_JFF2000", { "MIC_jff_init", "MIC_jff_intro", "MIC_jff_go", "MIC_jff_end", "MIC_jff_jump" }},
    {"MIC_AGO2000", { "MIC_ship_init", "MIC_dec_go", "MIC_tir_go", "MIC_en1_go", "MIC_en1_paf", "MIC_bul_enn_go", "MIC_en4_go", "MIC_en5_go", "MIC_en6_go", "MIC_flash", "DS1_power_up", "DS1_en9_go" }},
    {"Levelvulca_10", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"OLD_janold", { "OLD_ja_init", "OLD_ja_mort", "OLD_ja_enfoui", "OLD_ja_MAIN", "OLD_ja_tourne_wp", "OLD_ja_tourne_rm", "OLD_ja_boule_feu", "OLD_ja_attend", "OLD_ja_declencheur", "OLD_ja_cherch_wp", "OLD_ja_init2", "OLD_ja_vide", "OLD_ja_attrap", "old_ja_fin", "old_ja_out", "old_ja_enfoui2" }},
    {"OLD_interupt_acteurs", { "OLD_inter_init", "OLD_inter_surveille", "DS1_TempoVeille" }},
    {"OLD_vlc_platform", { "NFP_vlcpf_init", "OLD_vlcpf_active" }},
    {"OLD_jano_bras", { "OLD_jan_bras_init", "OLD_jan_bras_main", "OLD_jan_bras_mort_rm", "OLD_jan_bras_porte_rm", "old_jan_bras_vide", "old_jan_bras_attend", "DS1_JeFaisLaGueuleApresUnPaf" }},
    {"OLD_Main_PF", { "OLD_MPF_init", "OLD_MPF_deplace", "OLD_MPF_waitRM", "OLD_MPF_vide", "SDZ_MPF_AttenteRM", "SDZ_MPF_Up", "SDZ_MPF_Down" }},
    {"OLD_murs_entre2", { "OLD_mur_entre2_init", "OLD_mur_entre2_ouvert", "OLD_mur_entre2_souvre" }},
    {"FRH_porte", { "FRH_po_init", "FRH_po_ouvert", "FRH_po_ferme" }},
    {"OLD_crystaux", { "OLD_cristaux_init", "OLD_cristaux_attent" }},
    {"OLD_pf_tournante", { "OLD_pf_tournante_init", "OLD_pf_tournante_main" }},
    {"OLD_pf_volcan", { "OLD_pf_volcan_init", "OLD_pf_volcan_chute", "OLD_pf_volcan_glisse", "OLD_pf_volcan_retourn", "OLD_pf_volcan_init2" }},
    {"OLD_crane", { "OLD_crane_init" }},
    {"OLD_mv_colonne", { "OLD_mv_colon_init", "OLD_mv_colon_enfonc", "XAP_Fin" }},
    {"OLD_crane_shoot", { "OLD_crane_shoot_init", "OLD_crane_shoot_go", "OLD_crane_shoot_fixe", "OLD_crane_shoot_delete", "OLD_crane_shoot_lance", "OLD_crane_shoot_tombe", "OLD_crane_shoot_tourne", "SDZ_crane_shoot_vibration" }},
    {"Levelvulca_20", { "YLT_InitLevel", "DS1_LevelLoop" }},
    {"OLD_bouche_jano", { "OLD_bouche_init", "OLD_bouche_main", "OLD_bouche_wait", "OLD_bouche_mort", "DS1_bouche_attend", "MIC_bouche_croque", "DS1_TryAgain", "DS1_Bouche_ComportementVide" }},
    {"OLD_jano_boss", { "OLD_jan_boss_init", "OLD_jan_boss_boule_feu", "OLD_jan_boss_attend", "OLD_jan_boss_saut", "OLD_jan_boss_rotation", "OLD_jan_boss_reception", "OLD_jan_boss_rot_rm", "OLD_jan_boss_vide", "OLD_jan_boss_marche", "OLD_jan_boss_crane", "OLD_jan_boss_attend_crane", "OLD_jan_boss_main1", "OLD_jan_boss_main2", "OLD_jan_boss_main3", "OLD_jan_boss_main4", "OLD_jan_boss_main5", "OLD_jan_boss_main6", "OLD_jan_boss_main7", "OLD_jan_boss_main8", "OLD_jan_boss_main9", "OLD_jan_boss_main10", "OLD_jan_boss_main11", "OLD_jan_boss_main_fin", "DS1_jan_boss_main67" }},
    {"MOM_Ray_Vulca12_model", { "MOM_Ray_Vulca12_init", "MOM_Ray_Vulca12_THX" }},
    {"SDZ_Choix", { "SDZ_Choix_0_Init", "SDZ_Choix_1_Attente", "SDZ_Choix_2_FadeIn", "SDZ_Choix_3_Choix", "SDZ_Choix_4_FadeOut" }},
    {"LevelWater_10", { "YLT_InitLevel", "DS1_Loop" }},
    {"STN_Porto", { "STN_Porto_init", "STN_Porto_check_switch1", "STN_Porto_check_switch2", "STN_Porto_tremble", "STN_Porto_ouvre_toi", "STH_DejaOuvert" }},
    {"STH_trigger", { "STH_trigger_init" }},
    {"Levelwater_20", { "YLT_InitLevel", "STN_Level_boucleAOJ", "STN_Level_Attente_Gwod", "STN_Level_debutAOJ", "STN_Level_finAOJ", "STH_AGOneigeenboucle" }},
    {"MIC_Porto", { "MIC_porto_INIT", "MIC_porto_Surveille", "MIC_porto_interrupteur" }},
    {"STN_ouodeugwod", { "STN_ouodeugwod_init", "STN_ouodeugwod_dead", "STN_ouodeugwod_move", "STN_ouodeugwod_shoot", "STN_ouodeugwod_happy", "STN_ouodeugwod_titre_debut", "STN_ouodeugwod_titre_boucle", "STN_ouodeugwod_titre_fin", "DS1_PanDansLaGueule" }},
    {"MOM_Ray_Water20", { "MOM_Ray_water20_init", "MOM_Ray_Water20_THX" }},
    {"STN_Aglagla", { "STN_Aglagla_chute", "STN_Aglagla_init", "STN_Aglagla_PAF", "STN_Aglagla_the_end", "STN_Aglagla_vise", "STN_Aglagla_wait" }},
    {"STN_direction", { "STN_direction_init", "STN_direction_fade", "STN_direction_switch" }},
    {"STN_Stalac_shoot", { "STN_Stalac_Shoot_init", "STN_Stalac_Shoot_lums", "STN_Stalac_Shoot_fire" }},
    {"LevelWhale_00", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"MIC_Piranha_NiakVarappe", { "MIC_Piranha_NV_INIT", "MIC_Piranha_NV_Surveille", "MIC_Piranha_NV_Attak", "MIC_Piranha_NV_Delai", "MIC_Piranha_NV_Rebond" }},
    {"STN_kisscoule", { "STN_kisscoule_init", "STN_kisscoule_waypoint1", "STN_kisscoule_waypoint2", "STN_kisscoule_waypoint3", "STN_kisscoule_goway2", "STN_kisscoule_goway3", "STN_kisscoule_goway1" }},
    {"XAP_Plouf", { "XAP_Plouf_init" }},
    {"XAP_TonoGear_light", { "XAP_Tonolight_init", "XAP_alarme", "XAP_Tonolight_chemin", "XAP_Tonolight_fire", "XAP_Tonolight_fire_Ray", "XAP_Tonolight_fixe", "XAP_Tonolight_Laser" }},
    {"MIC_LumsBulle", { "MIC_Lums_Bulle_Init", "MIC_Lums_Bulle_Main" }},
    {"Levelwhale_05", { "YLT_InitLevel", "YLT_LevelLoop" }},
    {"CHR_Baleine_a_bulles", { "CHR_Baleine_Init", "PHL_Baleine_Wait", "PHL_Baleine_Suit_Reseau", "PHL_Baleine_Fin_Reseau" }},
    {"MIC_PiranhaGobeBulle", { "MIC_PiranhaGB_INIT", "MIC_PiranhaGB_AttendBulle", "MIC_PiranhaGB_ChasseBulle", "MIC_PiranhaGB_pause", "MIC_PiranhaGB_RelacheLesBulles" }},
    {"PHL_Baleine_Bouillon", { "PHL_Bouillon2Baleine_Init" }},
    {"LevelWhale_10", { "YLT_InitLevel", "YLT_LevelLoop" }}
};

const std::unordered_map<std::string, std::vector<std::string>> reflexNames = {
    {"Alw_Explosion_model", {  }},
    {"ELR_mLaveBloup", {  }},
    {"LevelAstro_00", {  }},
    {"MIC_Obus_Complexe", { "MIC_ObusC_RSansReseau", "MIC_ObusC_RAvecReseau", "MIC_ObusC_RVide" }},
    {"CHR_lums_basic", {  }},
    {"MIC_FinDeMap_Simple", {  }},
    {"OLD_porte", {  }},
    {"CHR_tronc_pic", {  }},
    {"MIC_SbireNinja", {  }},
    {"MIC_GenNFumees", {  }},
    {"ARG_MegaShoot", {  }},
    {"SUN_Cam_Oriente", {  }},
    {"FRG_Generateur", {  }},
    {"SDZ_EtatAOJ", { "DS1_EtatRfx_0_JeBulle", "DS1_EtatRfx_1_FollowRayman" }},
    {"MIC_CameraCinoche", {  }},
    {"MIC_RetientRay", {  }},
    {"DS1_BouclantGlobal", {  }},
    {"OLD_interrupteur", {  }},
    {"Alw_Lums_Model", {  }},
    {"YLT_RaymanModel", { "BNT_ReflexeMort", "YLT_AucunReflexe", "YLT_SautDetecteSol", "YLT_ReflexeAttente", "YLT_SautCourant", "JAC_GiReflexe", "BNT_ReflexeNage", "BNT_ReflexeGrappin", "CHG_VarREflexe", "FRD_Entr2Reflexe", "BNT_TonneauFuseeReflexe", "BNT_ReflexeDansLeSiegeRusse", "BNT_ReflexeTonneauPorte", "YLT_ReinitReflexe", "BNT_ReflexePatin", "BNT_SautImpulsionReflexe" }},
    {"StdCam", { "CHR_Reflexe" }},
    {"GlobalActorModel", {  }},
    {"YAM_GenMenuMap", { "YAM_MapNeRienFaire", "YAM_MapGestionModifValeur", "YAM_MapGestionMenuStandard", "MCK_MapGestionModifValeurLum", "MCK_MapGestionMultiPage", "MCK_MapGestionMenuYesNo", "NIK_R_LitPad", "NIK_JFF_LITPAD" }},
    {"ARG_IconeGestionnaire", {  }},
    {"Alw_Projectile_Rayman_model", {  }},
    {"CHG_TexteMenu", {  }},
    {"ARG_FondMenu", {  }},
    {"YAM_LumsCurseur", { "YAM_LumsCurseur0Deformation" }},
    {"Alw_Faisceau_Model", { "OLD_faisceau_temp", "OLD_reflexe_vide" }},
    {"DS1_OneShot", {  }},
    {"LevelAstro_10", {  }},
    {"MIC_Tir_Starwars", {  }},
    {"ARG_SerieRouge", {  }},
    {"ARG_SerieLums", {  }},
    {"MIC_EclaboussuresObus", {  }},
    {"ARG_Rayseau", {  }},
    {"LevelBall", {  }},
    {"OLD_francesco", {  }},
    {"ARG_DebutDeMap", {  }},
    {"Alw_Plouf_Model", {  }},
    {"MOM_Ray_Bast10", {  }},
    {"LevelBast_09", {  }},
    {"STN_cam_pluie", {  }},
    {"STN_Sofkipleu", {  }},
    {"MOM_pirate_sbire_cine_2", {  }},
    {"THX_BlaBla", { "SUN_Blabla_RFX" }},
    {"OLD_THX", {  }},
    {"MOM_porteCine_bast10", {  }},
    {"FRH_sbire_gnak", { "FRH_sol_collision", "FRH_sol_rien", "FRH_sol_saut", "FRH_sol_courir" }},
    {"LevelBast_10", {  }},
    {"CHR_Porte", { "DS1_RfxVide", "DS1_RfxCadre" }},
    {"OLP_PlotKiTombe", {  }},
    {"SUN_PosCam_Smooth", {  }},
    {"OLP_Switch_Auto", {  }},
    {"SUN_PosCam_Cut", {  }},
    {"MIC_GorilleGardien", {  }},
    {"BNT_EnferDeDante", {  }},
    {"CHR_CheckP", {  }},
    {"VCT_GenPrune", {  }},
    {"OLD_SBIRE_shoot_sol", { "SUN_SB_shoot_Rsol", "SUN_SB_shoot_Rrien", "SUN_SB_shoot_Rchute" }},
    {"STN_SaveSwitch", {  }},
    {"JEZ_lumiere", {  }},
    {"MIC_fleche_helpeuse", {  }},
    {"STH_teleport", {  }},
    {"SDZ_SteleAOJ", { "SDZ_0_Je_Bulle", "SDZ_1_Je_Filme", "DS1_2_FollowRayman" }},
    {"YAM_PastilleVersLaMapMonde", {  }},
    {"JCP_dead_perso", {  }},
    {"MIC_GenCamera", {  }},
    {"IVN_DebutDeMap", {  }},
    {"DS1_SonBast10", {  }},
    {"OLD_ptitchampi", {  }},
    {"ARG_Papillon", {  }},
    {"STN_kipik", {  }},
    {"STH_controleSC", {  }},
    {"IVN_poisson_drole", {  }},
    {"ARG_NageDevantRM", {  }},
    {"JEZ_LeMoulin", {  }},
    {"JEZ_plateHelice", {  }},
    {"OLD_alw_tonneau_model", {  }},
    {"BNT_ThePrune", { "BNT_Reflex_PruneVide", "BNT_Reflex_PruneQuiFlotte", "BNT_Reflex_PrunePortee", "DS1_Rfx_PruneEnChuteBast", "DS1_Rfx_PruneEnChutePlum", "DS1_Rfx_PruneEnChuteMine", "DS1_Rfx_PruneEnChuteLearn", "DS1_Rfx_PrunePlumAccrochablePasPrunable" }},
    {"SUN_basic", {  }},
    {"LevelBast_20", {  }},
    {"OLP_PorteLaser_Switch", {  }},
    {"CEB_porte_bois", {  }},
    {"STN_sparadrap_metal", {  }},
    {"SUN_Tono_Generator", {  }},
    {"BNT_TonneauFusee", { "BNT_ReflexeTonneauRamassable", "BNT_ReflexeTonneauRamasse", "BNT_ReflexeTonneauFusee", "MIC_ReflexeTonneauVide", "DS1_ReflexeTonneauParTerre", "DS1_RaymanMeRamasse" }},
    {"ARG_CageLums", {  }},
    {"MIC_BancDePiranhas_NoCollision", {  }},
    {"MIC_sparadrap", {  }},
    {"MIC_PiranhaSauteurVisible", { "MIC_PSV_MangeDuPaf", "MIC_PSV_RRien" }},
    {"MIC_BoiteDisco", {  }},
    {"GRP_Trampoline", {  }},
    {"STN_pontlevis", {  }},
    {"OLP_Inverseur", {  }},
    {"DS1_RegleurInertie", {  }},
    {"SDZ_MurfyAOJ", { "SDZ_AOJ_0_JeBulle", "SDZ_AOJ_1_JeCommenceAFilmer", "SDZ_AOJ_2_JeFilme", "SDZ_AOJ_3_NoReflex" }},
    {"OLP_IA_bzzz_IA", {  }},
    {"OLP_DetruitCamera", {  }},
    {"OLP_Gendoor_Detruit_Tonneau_R40", {  }},
    {"IVN_Simple_Granouil", {  }},
    {"OLD_fumee_toxique", { "OLD_fumee_tox_Rrien", "OLD_fumee_tox_R_collision" }},
    {"STH_petitspiranha_deco", {  }},
    {"Alw_Feu_model", {  }},
    {"LevelBast_22", {  }},
    {"STN_bombginreita", {  }},
    {"OLP_Nuages_Generateur_Model", {  }},
    {"IVP_Foudre", {  }},
    {"FRD_EntreDeux", {  }},
    {"MOM_missileCine", {  }},
    {"MIC_LanceBanane", {  }},
    {"SDZ_Ly_Cine", {  }},
    {"SDZ_RayDum", {  }},
    {"SUN_Lums_Cinema", {  }},
    {"SDZ_FX_Bast20", {  }},
    {"OLP_Timing_Active_Aide", {  }},
    {"BNT_grappinable", { "PHL_Rfx_Recuperation", "ARG_Rfx_EnGrappin", "ARG_Rfx_NonAccrochable", "DS1_Rfx_None" }},
    {"Alw_Bombe_Model", { "IVN_teste_collision_avec_parois", "IVN_bombe_vide" }},
    {"LevelBatam_10", {  }},
    {"MOM_batam_cine", {  }},
    {"SUN_Pir_Barbu_Cinema", {  }},
    {"SUN_Pir_Chaise_Cine", {  }},
    {"SUN_Pir_Lun_Cinema", {  }},
    {"NIK_Nef_Cine_THX", {  }},
    {"MOM_Ray_bat10", {  }},
    {"YAM_GenCompteurCine", {  }},
    {"SUN_CamAnim_THX", {  }},
    {"NIK_GEN_NIK", {  }},
    {"SDZ_Porte_Cine", {  }},
    {"LevelBatam_20", {  }},
    {"THX_Spielberg", {  }},
    {"SDZ_SpecialFX", {  }},
    {"SDZ_General_Cine", {  }},
    {"SDZ_Coffre_Cine", {  }},
    {"SDZ_Rhoppy", { "SDZ_RhopRfx_0_Init", "SDZ_RhopRfx_1_Flammes" }},
    {"IVN_simple_bat", {  }},
    {"YLT_Actor_Model1", {  }},
    {"Levelboat01", {  }},
    {"OLD_helice", {  }},
    {"ECO_au_revoir_rayman", {  }},
    {"Levelboat02", {  }},
    {"FRH_tremplin", {  }},
    {"SUN_Barriere_Laser", {  }},
    {"SDZ_Wind", {  }},
    {"Alw_Fumee_model", {  }},
    {"OLD_alphabet", {  }},
    {"Levelbonux", { "MIC_World_RInit", "MIC_World_RNormal", "MIC_World_RAntiStart" }},
    {"MIC_Bebe_Bonux", {  }},
    {"MIC_CameraCircuit", {  }},
    {"MIC_LunetteBonux", {  }},
    {"MIC_LudiBonux", {  }},
    {"OLD_bebe_globox", {  }},
    {"levelCask_10", {  }},
    {"SUN_Cam_AxeForce", {  }},
    {"MIC_GerbeTonneau", {  }},
    {"MIC_ZigouillateurNPersos", {  }},
    {"MIC_ActivateurMultiple", {  }},
    {"GRP_GratificationAnim", {  }},
    {"STN_planches", { "IVN_planche_rfx_void", "IVN_planche_rfx_rumble" }},
    {"LevelCask_30", {  }},
    {"MIC_StarTrek", {  }},
    {"MIC_GrilleInterruptee", {  }},
    {"MIC_Killeur", {  }},
    {"STN_batokipass", {  }},
    {"ARG_Ptizetre", {  }},
    {"STN_varappe", { "DS1_Varape_Rumble_Rfx", "DS1_Varape_Rfx_vide" }},
    {"Alw_Projectile_model", {  }},
    {"LevelChase_10", {  }},
    {"STN_bato", { "STN_bato_commande" }},
    {"STN_genbato", {  }},
    {"OLD_pouletzombie", { "OLD_poulzomb_reflex", "OLD_poulzomb_Rrien" }},
    {"DS1_PastilleAPeage", {  }},
    {"DS1_ZyvaEnvoieTesLums", {  }},
    {"DS1_Ly_Potiche", {  }},
    {"OLD_tonneau_reseau", {  }},
    {"OLD_ponton", { "IVN_ponton_rfx_void", "IVN_ponton_rfx_rumble" }},
    {"MIC_PasserelleMarais", {  }},
    {"STN_bato_boulet", {  }},
    {"STN_boulet_surprise", {  }},
    {"DS1_Missile_direct", {  }},
    {"DS1_Missile_Chrono", {  }},
    {"LevelChase_22", {  }},
    {"ARG_SimpleSbire", { "ARG_Rvide", "ARG_Rpoing" }},
    {"ARG_Gen_Tono_Roule", {  }},
    {"SUN_Damocles", {  }},
    {"ARG_Tonneau_DonkeyKong", {  }},
    {"LevelEarth_10", {  }},
    {"ARG_Chenille_Reseau", { "ARG_Rfx_Inoffensive", "ARG_Rfx_Mechante", "ARG_Rfx_NonVisible" }},
    {"MIC_PiranhaHaineux", {  }},
    {"OLD_SBIRE_alarme", { "OLD_SBIRE_alarme_Rsol", "OLD_SBIRE_alarme_Rrien" }},
    {"MIC_OctusDiabolus", {  }},
    {"MIC_MaturinDesMarais", {  }},
    {"LevelEarth_20", {  }},
    {"SUN_Cam_Suivi", {  }},
    {"SUN_BouchaFeu", {  }},
    {"SUN_Interrupteurs", {  }},
    {"SUN_Mur_Ronce", {  }},
    {"IVP_ActiveTunnel", {  }},
    {"IVP_Plateforme", {  }},
    {"OLD_mur_a_eclater", {  }},
    {"SUN_Porte_Simple", {  }},
    {"SUN_PLF_Plate", {  }},
    {"SUN_PLF_Pilier", {  }},
    {"SUN_PtiteRonce", {  }},
    {"LevelEarth_30", {  }},
    {"STN_Spoutz_generator", {  }},
    {"OLD_coulee_lave", {  }},
    {"MIC_MurKiBouge", {  }},
    {"SUN_Porte_Terre", { "DS1_Test_Interrupteur" }},
    {"OLD_tterre_colon_pivot", {  }},
    {"OLD_t_petite_colon", {  }},
    {"OLD_flaque_plouf_lave", {  }},
    {"STN_kapoueh", {  }},
    {"levelEnd_10", {  }},
    {"SDZ_RayPlik", {  }},
    {"OLP_Interrupteur_Modele1", {  }},
    {"OLD_mas_broken", {  }},
    {"ARG_Tremble", {  }},
    {"OLP_PlanteMorph_Modele1", {  }},
    {"MIC_FlammeGlobosk", {  }},
    {"ARG_AttaqueGlobox", {  }},
    {"ARG_SansVie", {  }},
    {"ARG_Fast_Globox", {  }},
    {"SUN_Grille_Cage", {  }},
    {"JEZ_PorteLaser", { "CHR_PL_Rfx_CheckNuage", "CHR_PL_Rfx_CreeNuage", "CHR_PL_NoRfx", "ARG_PL_Rfx_AttenteFoudre" }},
    {"GRP_Fin_Glob_10", {  }},
    {"Levelglob_10", {  }},
    {"MIC_CheckPointAccessoire", {  }},
    {"SDZ_Glob_Cine", {  }},
    {"OLP_PlateForme_Fleur", {  }},
    {"CHR_BuissonCacheur", {  }},
    {"GRP_Assaut_Nef", {  }},
    {"LevelGlob_20", {  }},
    {"SUN_Globox_Cinema", {  }},
    {"NIK_Ray_Glob20", {  }},
    {"ARG_SpotAuSol", {  }},
    {"LevelGlob_30", {  }},
    {"ARG_Araignee", { "ARG_Vide", "ARG_Paf" }},
    {"ARG_Transparence_Light", {  }},
    {"Levelhelic_10", {  }},
    {"SUN_GenWind_Mod", {  }},
    {"SUN_Pyramide_Feu", {  }},
    {"STN_Portaykl_ginreita", {  }},
    {"STN_viseur", {  }},
    {"STN_dogcam", {  }},
    {"SDZ_Ray_Helic10", {  }},
    {"SDZ_Porte_Helic20_Cine", {  }},
    {"SDZ_RayZin", {  }},
    {"NIK_garde_tfeu_cine", {  }},
    {"Levelhelic_20", {  }},
    {"MIC_NoFreeLookBordel", {  }},
    {"LevelHelic_30", {  }},
    {"STN_fayagwod", {  }},
    {"STN_Railcam", {  }},
    {"STN_pied_jack_on", {  }},
    {"NIK_Ray_Helic30", {  }},
    {"SUN_Cam_Distance", {  }},
    {"Levelile_10", {  }},
    {"MIC_MenhirSauteur", {  }},
    {"MIC_GenNInterrupteurs", {  }},
    {"MIC_GoretsEnPrison", {  }},
    {"MIC_CaisseFlottante", {  }},
    {"MIC_SuperPoussin", {  }},
    {"IVN_nef_cine_intro", { "IVN_nef_main_loop", "IVN_nef_init_ref" }},
    {"LevelJail_10", {  }},
    {"IVN_incline_cam_dans_cine", { "IVN_main_loop", "MOM_gen_cin_rfx_init" }},
    {"MOM_eboulisMod", {  }},
    {"MOM_ray2tgeMod", {  }},
    {"SUN_Ray_Logos", {  }},
    {"OLD_Helice01", {  }},
    {"Leveljail_20", {  }},
    {"SUN_Barriere_Laser_Cine", {  }},
    {"SUN_RayDummy_Intro", {  }},
    {"SUN_Grille_Cine", {  }},
    {"SUN_Sbire_Glob_Cine", {  }},
    {"SUN_Papillon", {  }},
    {"SUN_3B_Globox_Cine", {  }},
    {"SDZ_Ray_Learn60", {  }},
    {"MIC_LeverDuJour", {  }},
    {"SDZ_FinLearn10", { "DS1_Desactivator", "DS1_JeGlande" }},
    {"YAM_GenPoloc", {  }},
    {"ARG_Transparence", {  }},
    {"STH_TargetCam", { "STH_targe_vide", "STH_target_ago" }},
    {"LevelLearn_10", {  }},
    {"SDZ_Pitizetre_Cine", {  }},
    {"SUN_Poisson_Rigol_M", {  }},
    {"DS1_pti", {  }},
    {"DS1_OneShotCondition", {  }},
    {"DS1_SwitchBouclant", {  }},
    {"PHL_Actor_Model2", {  }},
    {"LevelLearn_30", {  }},
    {"LevelLearn_31", {  }},
    {"ELR_mPrisme", { "ELR_R_Prisme_00Init", "ELR_R_Prisme_01_Normal" }},
    {"BNT_BancDePetitsPiranhasTeigneux", {  }},
    {"SUN_Barriere_Elec", {  }},
    {"LevelLearn_40", {  }},
    {"DS1_GestionPaireInterrupteur", {  }},
    {"IVN_Sbire_Bombe", { "IVN_sol_collision", "IVN_sol_rien", "IVN_sol_saut", "IVN_sol_courir" }},
    {"STN_stilwil", {  }},
    {"LevelLearn_60", {  }},
    {"OLP_Vent_Vertical", {  }},
    {"MIC_GenSalleMagique", {  }},
    {"LevelLiber_10", {  }},
    {"SUN_ToutLeMondeIlEstLibre", { "SUN_BrisonsNosChaines" }},
    {"SUN_FautFilmerToutCa", { "SUN_EnleveLeCache_Init", "SUN_EnleveLeCache_THX" }},
    {"SUN_check_point", {  }},
    {"LevelLy_10", {  }},
    {"OLD_fee_ly", {  }},
    {"GRP_HorsLimite", {  }},
    {"GRP_TimerCourse", { "DS1_LivrePoloc", "DS1_Tempo", "DS1_BruitagInterdiction" }},
    {"GRP_CestFini", {  }},
    {"DS1_Affichage", {  }},
    {"GRP_Toile_Trampoline", {  }},
    {"CHR_Apparition", { "CHR_Apparition_Init" }},
    {"LevelLy_20", {  }},
    {"GRP_Generateur_Nenuphar", {  }},
    {"OLD_nenuphar", {  }},
    {"YAM_RayMonde", { "YAM_R_RayMonde0Attend", "YAM_R_RayMonde1Cours", "YAM_R_RayMonde2Saute", "YAM_R_RayMonde3Glisse", "YAM_R_RayMonde0Chute" }},
    {"LevelMapmonde2", {  }},
    {"YAM_GenInitMapmonde", { "YAM_R_GenInitMapmonde0Noir", "YAM_R_GenInitMapmonde1Normal" }},
    {"YAM_PastilleMapmonde2", {  }},
    {"NIK_GenAutoSave", {  }},
    {"NIK_Gen_EcranStart", { "NIK_R_CheatCode", "NIK_R_NeRienFaire" }},
    {"Levelmenu", {  }},
    {"YAM_Baleine", {  }},
    {"YAM_PtizetreMenu", {  }},
    {"MIC_Krab", {  }},
    {"YAM_GenMenuSimple", { "YAM_R_GenMenuSimple_Standard", "YAM_R_GenMenuSimple_NeRienFaire", "YAM_R_GenMenuSimple_Jauge", "YAM_R_GenMenuSimple_Switch", "YAM_R_GenMenuSimple_Slot", "NIK_R_GenMenuSimple_YesNo", "NIK_R_GenMenuSimple_LitPad", "NIK_JFF_R_GenMenuSimple_LitPadSansCadre" }},
    {"YAM_GenCibleCamera", { "YAM_GenCibleCamera1ScruteMenu", "YAM_GenCibleCamera0NeRienFaire" }},
    {"ARG_Martin_Pecheur", {  }},
    {"NIK_Popolipoi_Menu_DC", {  }},
    {"Levelmine_10", {  }},
    {"MIC_Nef_ARaymond", {  }},
    {"MIC_QuaiPourNef", {  }},
    {"OLD_bastion_cassable", {  }},
    {"MIC_TesteNefPleine", {  }},
    {"MOM_Ray_Mines10_model", {  }},
    {"MOM_mines10F", {  }},
    {"MOM_Globette_Cine_Mod", {  }},
    {"MOM_Collision", {  }},
    {"MIC_GoretsMineurs", {  }},
    {"Levelmorb_00", {  }},
    {"ARG_Vase_Flotte", {  }},
    {"ARG_BrasJano", { "ARG_RBJ_Vide", "ARG_RBJ_CheckTout", "ARG_RBJ_CheckPoing" }},
    {"OLD_SBIRE_lance", { "OLD_SBIRE_lance_Rsol", "OLD_SBIRE_lance_Rrien" }},
    {"SUN_engrenage", {  }},
    {"SUN_grillio", {  }},
    {"Levelmorb_10", {  }},
    {"DS1_Change_Map", {  }},
    {"XAP_World_SM1", {  }},
    {"XAP_World_SM2", { "XAP_check" }},
    {"XAP_World_SM3", {  }},
    {"MIC_SauveCB28", {  }},
    {"XAP_Figntable", {  }},
    {"OLD_tonneau_vase", {  }},
    {"LevelMorb_20", { "ARG_DefaultReflex", "ARG_NullReflex", "ARG_MusicReflex" }},
    {"SUN_Clarky", {  }},
    {"SUN_Cine_Ray_Clark", { "YGE_CineClark_Skip" }},
    {"XAP_Check_Inter", {  }},
    {"DS1_Offset_Perso", {  }},
    {"STH_cible", {  }},
    {"SUN_RayDum_Clark", {  }},
    {"LevelNave_10", {  }},
    {"STN_filetGI", { "DS1_Filet_Rumble_Rfx", "DS1_Filet_Rfx_Vide" }},
    {"STN_pitibastion", { "DS1_bast_rumble_rfx", "DS1_bast_rfx_vide" }},
    {"STN_pont", { "DS1_pont_rumble_rfx", "DS1_pont_rfx_vide" }},
    {"LevelNave_15", {  }},
    {"DS1_WaterQuiMonte", {  }},
    {"STH_grue_tour", {  }},
    {"MIC_GenTuePirateALeau", {  }},
    {"STH_28", {  }},
    {"STH_generateur_boulets", {  }},
    {"LevelNave_20", {  }},
    {"STH_vie_eternelle", {  }},
    {"Levelnego_10", {  }},
    {"NIK_Ray_Nego", {  }},
    {"NIK_Porte_Ptizetre", {  }},
    {"NIK_Ptizetre_nego_cine", {  }},
    {"LevelPlum_00", {  }},
    {"MIC_MonstroPlante", { "MIC_MP_RVide", "MIC_MP_RPaf", "MIC_MP_RRien" }},
    {"CHR_inter", {  }},
    {"MIC_RadarTournant", {  }},
    {"YAL_plum00_2eSM", {  }},
    {"YAL_plum00_1ereSM", {  }},
    {"MIC_DalleCassee", {  }},
    {"YAL_Plum10_3eSM", {  }},
    {"SUN_magie_simple", {  }},
    {"ZOR_PyramideCrachante", {  }},
    {"SUN_magic_key", { "SUN_avant_porting", "SUN_pendant_porting", "SUN_rien" }},
    {"LevelPlum_10", {  }},
    {"STN_Aimant", {  }},
    {"STN_tour_nique", {  }},
    {"MIC_GeantVert", {  }},
    {"YAL_Plum10_2eSM", {  }},
    {"ALG_Plum10_4eSM", {  }},
    {"ALG_Plum10_1ereSM", {  }},
    {"MIC_TeleportKiCroyaitPrendre", {  }},
    {"MIC_Desactivateur", {  }},
    {"XAP_Apparition", {  }},
    {"XAP_Plum_teleport", {  }},
    {"DS1_Plum_Teleport2", {  }},
    {"DS1_Plum_Teleport3", {  }},
    {"MIC_TeteDuGeantVert", {  }},
    {"ZOR_CracheLave", {  }},
    {"Levelplum_20", {  }},
    {"BNT_StalagBase_Model", {  }},
    {"MIC_FireWorm", {  }},
    {"MIC_Rafteuse", {  }},
    {"MIC_Colonne", {  }},
    {"BNT_StalagPF_Model", {  }},
    {"LevelPoloc_10", {  }},
    {"NIK_Cine_Poloc", {  }},
    {"LevelPoloc_20", {  }},
    {"LevelPoloc_30", {  }},
    {"NIK_cine_poloc2", {  }},
    {"LevelPoloc_40", {  }},
    {"NIK_Gen_Raycap", {  }},
    {"LevelRaycap", {  }},
    {"DS1_gen_sound", {  }},
    {"LevelRhop_10", {  }},
    {"OLD_shoot_zde", {  }},
    {"OLD_shoot_laser_rouge", {  }},
    {"OLD_boule_energie", { "FRH_cb31", "FRH_cbfin" }},
    {"FRH_ouestu", {  }},
    {"DS1_teleport", {  }},
    {"FRH_Plaque_lave", { "FRH_RM_dead" }},
    {"SUN_Grille_Rhop_Cine", {  }},
    {"SUN_Boulet_Cine", {  }},
    {"SUN_RayRhop", {  }},
    {"SUN_Rhop_Cinema", {  }},
    {"SUN_Tuyo_ASC_Cine", {  }},
    {"SUN_Obus_Rhop", {  }},
    {"SUN_LY_Rhop", {  }},
    {"SUN_Lums_Rhop", {  }},
    {"SUN_Batam_Rhop", {  }},
    {"SUN_Flash_Cine", {  }},
    {"SUN_Nuage_cine", {  }},
    {"SUN_Debris_Cine", {  }},
    {"SUN_Reactivator2000", { "SUN_Reac2000_Init", "SUN_Reac2000_Phase1", "DS1_Reac2000_phase2" }},
    {"SUN_Interieur_Rhop_Cine", {  }},
    {"SUN_Rhop_MK1", { "OLD_rhop_accro_aie", "OLD_rhop_ref_vide", "OLD_rhop_shake", "FRH_rhop_sol_kill" }},
    {"FRH_AreYouTalkingtome", {  }},
    {"LevelRodeo_10", {  }},
    {"OLP_Detruit_Missile", {  }},
    {"OLP_Grille", {  }},
    {"MOM_murfyCine", {  }},
    {"DS1_BouclantCinematique", {  }},
    {"MOM_RayDum_encoreR10", {  }},
    {"OLP_DetruitPerso_A_Sa_Hauteur", {  }},
    {"LevelRodeo_40", {  }},
    {"JEZ_SlashRonce", { "JEZ_Slash_PafLaTronche" }},
    {"STN_Clarck_Eolog", {  }},
    {"STN_murMUR", {  }},
    {"SDZ_ClarkDum", {  }},
    {"SDZ_FX_Rodeo40", {  }},
    {"LevelRodeo_60", {  }},
    {"SUN_Jokari", {  }},
    {"MIC_MenhirBourre", {  }},
    {"SUN_ObusR60_Cine", { "DS1_Obus_R60_Rfx" }},
    {"SUN_GenSound_R60", {  }},
    {"SUN_Cam_R60_cine", {  }},
    {"Levelseat_10", {  }},
    {"BNT_SupportDuSiege", {  }},
    {"VIM_Gen_Siege_Russe", {  }},
    {"SDZ_PirateGorilleCine", {  }},
    {"SDZ_Ray_Seat10", {  }},
    {"VIM_Le_Gorille_tu_ecrases_hein", {  }},
    {"YLT_SiegeRusse", {  }},
    {"STN_Kapoum", {  }},
    {"STN_tonogear", {  }},
    {"LevelSeat_11", {  }},
    {"VIM_Cine_fin_seat_10", {  }},
    {"ARG_Cam_Tunnel_XY", {  }},
    {"VIM_Detect_n_persos", {  }},
    {"STN_boulet_moutarde", {  }},
    {"LevelSki_10", {  }},
    {"MIC_PtiPiranhaSolo", {  }},
    {"MIC_NewSerpentSki", {  }},
    {"MIC_NewRaymanSki", {  }},
    {"MIC_PouletFantome", {  }},
    {"MOM_Serpent_Ski_THX", {  }},
    {"MOM_JanoC_Vulca12", {  }},
    {"MIC_SuperCage", {  }},
    {"MIC_CamNoCol", {  }},
    {"MOM_Jano3", {  }},
    {"MOM_ski10", {  }},
    {"levelSki_60", {  }},
    {"MIC_BombeQuiTombe", {  }},
    {"MOM_ray_ski60", {  }},
    {"MIC_Tremplin", {  }},
    {"DS1_Staffman", {  }},
    {"DS1_staff_pirate", { "DS1_ref_cheat", "DS1_ref_vide" }},
    {"DS1_Goldorak", {  }},
    {"DS1_lamort", {  }},
    {"Levelstaff_10", { "DS1_cheat_world" }},
    {"DS1_go", {  }},
    {"MIC_JFF2000", { "MIC_jff_rien", "MIC_jff_generator" }},
    {"MIC_AGO2000", { "MIC_ref_vide" }},
    {"Levelvulca_10", {  }},
    {"OLD_janold", { "OLD_ja_r_zde", "OLD_ja_r_vide", "OLD_ja_r_fumee", "old_ja_r_cam", "old_ja_r_zde_wait" }},
    {"OLD_interupt_acteurs", {  }},
    {"OLD_vlc_platform", {  }},
    {"OLD_jano_bras", {  }},
    {"OLD_Main_PF", { "OLD_ref_rien", "OLD_ref_suivre" }},
    {"OLD_murs_entre2", {  }},
    {"FRH_porte", {  }},
    {"OLD_crystaux", {  }},
    {"OLD_pf_tournante", {  }},
    {"OLD_pf_volcan", {  }},
    {"OLD_crane", {  }},
    {"OLD_mv_colonne", {  }},
    {"OLD_crane_shoot", {  }},
    {"Levelvulca_20", {  }},
    {"OLD_bouche_jano", { "DS1_SelfDestruction", "DS1_SansReflexes" }},
    {"OLD_jano_boss", { "OLD_jan_boss_r_vide", "OLD_jano_boss_r_fumee" }},
    {"MOM_Ray_Vulca12_model", {  }},
    {"SDZ_Choix", {  }},
    {"LevelWater_10", {  }},
    {"STN_Porto", {  }},
    {"STH_trigger", {  }},
    {"Levelwater_20", {  }},
    {"MIC_Porto", {  }},
    {"STN_ouodeugwod", {  }},
    {"MOM_Ray_Water20", {  }},
    {"STN_Aglagla", {  }},
    {"STN_direction", {  }},
    {"STN_Stalac_shoot", {  }},
    {"LevelWhale_00", {  }},
    {"MIC_Piranha_NiakVarappe", {  }},
    {"STN_kisscoule", {  }},
    {"XAP_Plouf", {  }},
    {"XAP_TonoGear_light", {  }},
    {"MIC_LumsBulle", {  }},
    {"Levelwhale_05", {  }},
    {"CHR_Baleine_a_bulles", { "MIC_PHL_Baleine_RInit", "MIC_Baleine_RBubulles" }},
    {"MIC_PiranhaGobeBulle", { "MIC_PiranhaGB_RFaisBobo" }},
    {"PHL_Baleine_Bouillon", {  }},
    {"LevelWhale_10", {  }}
};
